// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Person.pb.h"

@implementation PersonRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PersonRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Person ()
@property (retain) NSString* name;
@property int32_t id;
@property (retain) NSString* email;
@property (retain) NSMutableArray* mutablePhoneList;
@end

@implementation Person

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value {
  hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
@synthesize mutablePhoneList;
- (void) dealloc {
  self.name = nil;
  self.email = nil;
  self.mutablePhoneList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.id = 0;
    self.email = @"";
  }
  return self;
}
static Person* defaultPersonInstance = nil;
+ (void) initialize {
  if (self == [Person class]) {
    defaultPersonInstance = [[Person alloc] init];
  }
}
+ (Person*) defaultInstance {
  return defaultPersonInstance;
}
- (Person*) defaultInstance {
  return defaultPersonInstance;
}
- (NSArray*) phoneList {
  return mutablePhoneList;
}
- (Person_PhoneNumber*) phoneAtIndex:(int32_t) index {
  id value = [mutablePhoneList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasId) {
    return NO;
  }
  for (Person_PhoneNumber* element in self.phoneList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasId) {
    [output writeInt32:2 value:self.id];
  }
  if (self.hasEmail) {
    [output writeString:3 value:self.email];
  }
  for (Person_PhoneNumber* element in self.phoneList) {
    [output writeMessage:4 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasName) {
    size += computeStringSize(1, self.name);
  }
  if (self.hasId) {
    size += computeInt32Size(2, self.id);
  }
  if (self.hasEmail) {
    size += computeStringSize(3, self.email);
  }
  for (Person_PhoneNumber* element in self.phoneList) {
    size += computeMessageSize(4, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Person*) parseFromData:(NSData*) data {
  return (Person*)[[[Person builder] mergeFromData:data] build];
}
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input {
  return (Person*)[[[Person builder] mergeFromInputStream:input] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person_Builder*) builder {
  return [[[Person_Builder alloc] init] autorelease];
}
+ (Person_Builder*) builderWithPrototype:(Person*) prototype {
  return [[Person builder] mergeFrom:prototype];
}
- (Person_Builder*) builder {
  return [Person builder];
}
@end

BOOL Person_PhoneTypeIsValidValue(Person_PhoneType value) {
  switch (value) {
    case Person_PhoneTypeMobile:
    case Person_PhoneTypeHome:
    case Person_PhoneTypeWork:
      return YES;
    default:
      return NO;
  }
}
@interface Person_PhoneNumber ()
@property (retain) NSString* number;
@property Person_PhoneType type;
@end

@implementation Person_PhoneNumber

- (BOOL) hasNumber {
  return !!hasNumber_;
}
- (void) setHasNumber:(BOOL) value {
  hasNumber_ = !!value;
}
@synthesize number;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value {
  hasType_ = !!value;
}
@synthesize type;
- (void) dealloc {
  self.number = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.number = @"";
    self.type = Person_PhoneTypeHome;
  }
  return self;
}
static Person_PhoneNumber* defaultPerson_PhoneNumberInstance = nil;
+ (void) initialize {
  if (self == [Person_PhoneNumber class]) {
    defaultPerson_PhoneNumberInstance = [[Person_PhoneNumber alloc] init];
  }
}
+ (Person_PhoneNumber*) defaultInstance {
  return defaultPerson_PhoneNumberInstance;
}
- (Person_PhoneNumber*) defaultInstance {
  return defaultPerson_PhoneNumberInstance;
}
- (BOOL) isInitialized {
  if (!self.hasNumber) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNumber) {
    [output writeString:1 value:self.number];
  }
  if (self.hasType) {
    [output writeEnum:2 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNumber) {
    size += computeStringSize(1, self.number);
  }
  if (self.hasType) {
    size += computeEnumSize(2, self.type);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Person_PhoneNumber*) parseFromData:(NSData*) data {
  return (Person_PhoneNumber*)[[[Person_PhoneNumber builder] mergeFromData:data] build];
}
+ (Person_PhoneNumber*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person_PhoneNumber*)[[[Person_PhoneNumber builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Person_PhoneNumber*) parseFromInputStream:(NSInputStream*) input {
  return (Person_PhoneNumber*)[[[Person_PhoneNumber builder] mergeFromInputStream:input] build];
}
+ (Person_PhoneNumber*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person_PhoneNumber*)[[[Person_PhoneNumber builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person_PhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Person_PhoneNumber*)[[[Person_PhoneNumber builder] mergeFromCodedInputStream:input] build];
}
+ (Person_PhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person_PhoneNumber*)[[[Person_PhoneNumber builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person_PhoneNumber_Builder*) builder {
  return [[[Person_PhoneNumber_Builder alloc] init] autorelease];
}
+ (Person_PhoneNumber_Builder*) builderWithPrototype:(Person_PhoneNumber*) prototype {
  return [[Person_PhoneNumber builder] mergeFrom:prototype];
}
- (Person_PhoneNumber_Builder*) builder {
  return [Person_PhoneNumber builder];
}
@end

@interface Person_PhoneNumber_Builder()
@property (retain) Person_PhoneNumber* result;
@end

@implementation Person_PhoneNumber_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Person_PhoneNumber alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Person_PhoneNumber_Builder*) clear {
  self.result = [[[Person_PhoneNumber alloc] init] autorelease];
  return self;
}
- (Person_PhoneNumber_Builder*) clone {
  return [Person_PhoneNumber builderWithPrototype:result];
}
- (Person_PhoneNumber*) defaultInstance {
  return [Person_PhoneNumber defaultInstance];
}
- (Person_PhoneNumber*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Person_PhoneNumber*) buildPartial {
  Person_PhoneNumber* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Person_PhoneNumber_Builder*) mergeFrom:(Person_PhoneNumber*) other {
  if (other == [Person_PhoneNumber defaultInstance]) {
    return self;
  }
  if (other.hasNumber) {
    [self setNumber:other.number];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Person_PhoneNumber_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Person_PhoneNumber_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setNumber:[input readString]];
        break;
      }
      case 16: {
        int32_t value = [input readEnum];
        if (Person_PhoneTypeIsValidValue(value)) {
          [self setType:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasNumber {
  return result.hasNumber;
}
- (NSString*) number {
  return result.number;
}
- (Person_PhoneNumber_Builder*) setNumber:(NSString*) value {
  result.hasNumber = YES;
  result.number = value;
  return self;
}
- (Person_PhoneNumber_Builder*) clearNumber {
  result.hasNumber = NO;
  result.number = @"";
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (Person_PhoneType) type {
  return result.type;
}
- (Person_PhoneNumber_Builder*) setType:(Person_PhoneType) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (Person_PhoneNumber_Builder*) clearType {
  result.hasType = NO;
  result.type = Person_PhoneTypeHome;
  return self;
}
@end

@interface Person_Builder()
@property (retain) Person* result;
@end

@implementation Person_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Person alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Person_Builder*) clear {
  self.result = [[[Person alloc] init] autorelease];
  return self;
}
- (Person_Builder*) clone {
  return [Person builderWithPrototype:result];
}
- (Person*) defaultInstance {
  return [Person defaultInstance];
}
- (Person*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Person*) buildPartial {
  Person* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Person_Builder*) mergeFrom:(Person*) other {
  if (other == [Person defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.mutablePhoneList.count > 0) {
    if (result.mutablePhoneList == nil) {
      result.mutablePhoneList = [NSMutableArray array];
    }
    [result.mutablePhoneList addObjectsFromArray:other.mutablePhoneList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 16: {
        [self setId:[input readInt32]];
        break;
      }
      case 26: {
        [self setEmail:[input readString]];
        break;
      }
      case 34: {
        Person_PhoneNumber_Builder* subBuilder = [Person_PhoneNumber builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPhone:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (Person_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (Person_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (Person_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (Person_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (Person_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (Person_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (NSArray*) phoneList {
  if (result.mutablePhoneList == nil) { return [NSArray array]; }
  return result.mutablePhoneList;
}
- (Person_PhoneNumber*) phoneAtIndex:(int32_t) index {
  return [result phoneAtIndex:index];
}
- (Person_Builder*) replacePhoneAtIndex:(int32_t) index with:(Person_PhoneNumber*) value {
  [result.mutablePhoneList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (Person_Builder*) addAllPhone:(NSArray*) values {
  if (result.mutablePhoneList == nil) {
    result.mutablePhoneList = [NSMutableArray array];
  }
  [result.mutablePhoneList addObjectsFromArray:values];
  return self;
}
- (Person_Builder*) clearPhoneList {
  result.mutablePhoneList = nil;
  return self;
}
- (Person_Builder*) addPhone:(Person_PhoneNumber*) value {
  if (result.mutablePhoneList == nil) {
    result.mutablePhoneList = [NSMutableArray array];
  }
  [result.mutablePhoneList addObject:value];
  return self;
}
@end

