// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Person;
@class Person_Builder;
@class Person_PhoneNumber;
@class Person_PhoneNumber_Builder;
typedef enum {
  Person_PhoneTypeMobile = 0,
  Person_PhoneTypeHome = 1,
  Person_PhoneTypeWork = 2,
} Person_PhoneType;

BOOL Person_PhoneTypeIsValidValue(Person_PhoneType value);


@interface PersonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Person : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasEmail_:1;
  int32_t id;
  NSString* name;
  NSString* email;
  NSMutableArray* mutablePhoneList;
}
- (BOOL) hasName;
- (BOOL) hasId;
- (BOOL) hasEmail;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* email;
- (NSArray*) phoneList;
- (Person_PhoneNumber*) phoneAtIndex:(int32_t) index;

+ (Person*) defaultInstance;
- (Person*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Person_Builder*) builder;
+ (Person_Builder*) builder;
+ (Person_Builder*) builderWithPrototype:(Person*) prototype;

+ (Person*) parseFromData:(NSData*) data;
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromInputStream:(NSInputStream*) input;
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Person_PhoneNumber : PBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasType_:1;
  NSString* number;
  Person_PhoneType type;
}
- (BOOL) hasNumber;
- (BOOL) hasType;
@property (readonly, retain) NSString* number;
@property (readonly) Person_PhoneType type;

+ (Person_PhoneNumber*) defaultInstance;
- (Person_PhoneNumber*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Person_PhoneNumber_Builder*) builder;
+ (Person_PhoneNumber_Builder*) builder;
+ (Person_PhoneNumber_Builder*) builderWithPrototype:(Person_PhoneNumber*) prototype;

+ (Person_PhoneNumber*) parseFromData:(NSData*) data;
+ (Person_PhoneNumber*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person_PhoneNumber*) parseFromInputStream:(NSInputStream*) input;
+ (Person_PhoneNumber*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person_PhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Person_PhoneNumber*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Person_PhoneNumber_Builder : PBGeneratedMessage_Builder {
@private
  Person_PhoneNumber* result;
}

- (Person_PhoneNumber*) defaultInstance;

- (Person_PhoneNumber_Builder*) clear;
- (Person_PhoneNumber_Builder*) clone;

- (Person_PhoneNumber*) build;
- (Person_PhoneNumber*) buildPartial;

- (Person_PhoneNumber_Builder*) mergeFrom:(Person_PhoneNumber*) other;
- (Person_PhoneNumber_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Person_PhoneNumber_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNumber;
- (NSString*) number;
- (Person_PhoneNumber_Builder*) setNumber:(NSString*) value;
- (Person_PhoneNumber_Builder*) clearNumber;

- (BOOL) hasType;
- (Person_PhoneType) type;
- (Person_PhoneNumber_Builder*) setType:(Person_PhoneType) value;
- (Person_PhoneNumber_Builder*) clearType;
@end

@interface Person_Builder : PBGeneratedMessage_Builder {
@private
  Person* result;
}

- (Person*) defaultInstance;

- (Person_Builder*) clear;
- (Person_Builder*) clone;

- (Person*) build;
- (Person*) buildPartial;

- (Person_Builder*) mergeFrom:(Person*) other;
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (Person_Builder*) setName:(NSString*) value;
- (Person_Builder*) clearName;

- (BOOL) hasId;
- (int32_t) id;
- (Person_Builder*) setId:(int32_t) value;
- (Person_Builder*) clearId;

- (BOOL) hasEmail;
- (NSString*) email;
- (Person_Builder*) setEmail:(NSString*) value;
- (Person_Builder*) clearEmail;

- (NSArray*) phoneList;
- (Person_PhoneNumber*) phoneAtIndex:(int32_t) index;
- (Person_Builder*) replacePhoneAtIndex:(int32_t) index with:(Person_PhoneNumber*) value;
- (Person_Builder*) addPhone:(Person_PhoneNumber*) value;
- (Person_Builder*) addAllPhone:(NSArray*) values;
- (Person_Builder*) clearPhoneList;
@end

