// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "CommandList.pb.h"

@implementation CommandListRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [CommandListRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Command ()
@property (retain) NSString* id;
@property (retain) NSString* name;
@end

@implementation Command

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value {
  hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (void) dealloc {
  self.id = nil;
  self.name = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.name = @"";
  }
  return self;
}
static Command* defaultCommandInstance = nil;
+ (void) initialize {
  if (self == [Command class]) {
    defaultCommandInstance = [[Command alloc] init];
  }
}
+ (Command*) defaultInstance {
  return defaultCommandInstance;
}
- (Command*) defaultInstance {
  return defaultCommandInstance;
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasName) {
    size += computeStringSize(2, self.name);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Command*) parseFromData:(NSData*) data {
  return (Command*)[[[Command builder] mergeFromData:data] build];
}
+ (Command*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Command*)[[[Command builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Command*) parseFromInputStream:(NSInputStream*) input {
  return (Command*)[[[Command builder] mergeFromInputStream:input] build];
}
+ (Command*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Command*)[[[Command builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Command*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Command*)[[[Command builder] mergeFromCodedInputStream:input] build];
}
+ (Command*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Command*)[[[Command builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Command_Builder*) builder {
  return [[[Command_Builder alloc] init] autorelease];
}
+ (Command_Builder*) builderWithPrototype:(Command*) prototype {
  return [[Command builder] mergeFrom:prototype];
}
- (Command_Builder*) builder {
  return [Command builder];
}
@end

@interface Command_Builder()
@property (retain) Command* result;
@end

@implementation Command_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Command alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Command_Builder*) clear {
  self.result = [[[Command alloc] init] autorelease];
  return self;
}
- (Command_Builder*) clone {
  return [Command builderWithPrototype:result];
}
- (Command*) defaultInstance {
  return [Command defaultInstance];
}
- (Command*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Command*) buildPartial {
  Command* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Command_Builder*) mergeFrom:(Command*) other {
  if (other == [Command defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Command_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Command_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (NSString*) id {
  return result.id;
}
- (Command_Builder*) setId:(NSString*) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (Command_Builder*) clearId {
  result.hasId = NO;
  result.id = @"";
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (Command_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (Command_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
@end

@interface CommandList ()
@property (retain) NSMutableArray* mutableCommandList;
@end

@implementation CommandList

@synthesize mutableCommandList;
- (void) dealloc {
  self.mutableCommandList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static CommandList* defaultCommandListInstance = nil;
+ (void) initialize {
  if (self == [CommandList class]) {
    defaultCommandListInstance = [[CommandList alloc] init];
  }
}
+ (CommandList*) defaultInstance {
  return defaultCommandListInstance;
}
- (CommandList*) defaultInstance {
  return defaultCommandListInstance;
}
- (NSArray*) commandList {
  return mutableCommandList;
}
- (Command*) commandAtIndex:(int32_t) index {
  id value = [mutableCommandList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  for (Command* element in self.commandList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (Command* element in self.commandList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (Command* element in self.commandList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CommandList*) parseFromData:(NSData*) data {
  return (CommandList*)[[[CommandList builder] mergeFromData:data] build];
}
+ (CommandList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CommandList*)[[[CommandList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CommandList*) parseFromInputStream:(NSInputStream*) input {
  return (CommandList*)[[[CommandList builder] mergeFromInputStream:input] build];
}
+ (CommandList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CommandList*)[[[CommandList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CommandList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CommandList*)[[[CommandList builder] mergeFromCodedInputStream:input] build];
}
+ (CommandList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CommandList*)[[[CommandList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CommandList_Builder*) builder {
  return [[[CommandList_Builder alloc] init] autorelease];
}
+ (CommandList_Builder*) builderWithPrototype:(CommandList*) prototype {
  return [[CommandList builder] mergeFrom:prototype];
}
- (CommandList_Builder*) builder {
  return [CommandList builder];
}
@end

@interface CommandList_Builder()
@property (retain) CommandList* result;
@end

@implementation CommandList_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CommandList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CommandList_Builder*) clear {
  self.result = [[[CommandList alloc] init] autorelease];
  return self;
}
- (CommandList_Builder*) clone {
  return [CommandList builderWithPrototype:result];
}
- (CommandList*) defaultInstance {
  return [CommandList defaultInstance];
}
- (CommandList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CommandList*) buildPartial {
  CommandList* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CommandList_Builder*) mergeFrom:(CommandList*) other {
  if (other == [CommandList defaultInstance]) {
    return self;
  }
  if (other.mutableCommandList.count > 0) {
    if (result.mutableCommandList == nil) {
      result.mutableCommandList = [NSMutableArray array];
    }
    [result.mutableCommandList addObjectsFromArray:other.mutableCommandList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CommandList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CommandList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Command_Builder* subBuilder = [Command builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addCommand:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) commandList {
  if (result.mutableCommandList == nil) { return [NSArray array]; }
  return result.mutableCommandList;
}
- (Command*) commandAtIndex:(int32_t) index {
  return [result commandAtIndex:index];
}
- (CommandList_Builder*) replaceCommandAtIndex:(int32_t) index with:(Command*) value {
  [result.mutableCommandList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (CommandList_Builder*) addAllCommand:(NSArray*) values {
  if (result.mutableCommandList == nil) {
    result.mutableCommandList = [NSMutableArray array];
  }
  [result.mutableCommandList addObjectsFromArray:values];
  return self;
}
- (CommandList_Builder*) clearCommandList {
  result.mutableCommandList = nil;
  return self;
}
- (CommandList_Builder*) addCommand:(Command*) value {
  if (result.mutableCommandList == nil) {
    result.mutableCommandList = [NSMutableArray array];
  }
  [result.mutableCommandList addObject:value];
  return self;
}
@end

