// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "DocTypeIdList.pb.h"

@implementation DocTypeIdListRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [DocTypeIdListRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface DocTypeIdList ()
@property (retain) NSMutableArray* mutableDocTypeIdList;
@end

@implementation DocTypeIdList

@synthesize mutableDocTypeIdList;
- (void) dealloc {
  self.mutableDocTypeIdList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static DocTypeIdList* defaultDocTypeIdListInstance = nil;
+ (void) initialize {
  if (self == [DocTypeIdList class]) {
    defaultDocTypeIdListInstance = [[DocTypeIdList alloc] init];
  }
}
+ (DocTypeIdList*) defaultInstance {
  return defaultDocTypeIdListInstance;
}
- (DocTypeIdList*) defaultInstance {
  return defaultDocTypeIdListInstance;
}
- (NSArray*) docTypeIdList {
  return mutableDocTypeIdList;
}
- (NSString*) docTypeIdAtIndex:(int32_t) index {
  id value = [mutableDocTypeIdList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (NSString* element in self.mutableDocTypeIdList) {
    [output writeString:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  {
    int32_t dataSize = 0;
    for (NSString* element in self.mutableDocTypeIdList) {
      dataSize += computeStringSizeNoTag(element);
    }
    size += dataSize;
    size += 1 * self.mutableDocTypeIdList.count;
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (DocTypeIdList*) parseFromData:(NSData*) data {
  return (DocTypeIdList*)[[[DocTypeIdList builder] mergeFromData:data] build];
}
+ (DocTypeIdList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DocTypeIdList*)[[[DocTypeIdList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DocTypeIdList*) parseFromInputStream:(NSInputStream*) input {
  return (DocTypeIdList*)[[[DocTypeIdList builder] mergeFromInputStream:input] build];
}
+ (DocTypeIdList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DocTypeIdList*)[[[DocTypeIdList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DocTypeIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (DocTypeIdList*)[[[DocTypeIdList builder] mergeFromCodedInputStream:input] build];
}
+ (DocTypeIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DocTypeIdList*)[[[DocTypeIdList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DocTypeIdList_Builder*) builder {
  return [[[DocTypeIdList_Builder alloc] init] autorelease];
}
+ (DocTypeIdList_Builder*) builderWithPrototype:(DocTypeIdList*) prototype {
  return [[DocTypeIdList builder] mergeFrom:prototype];
}
- (DocTypeIdList_Builder*) builder {
  return [DocTypeIdList builder];
}
@end

@interface DocTypeIdList_Builder()
@property (retain) DocTypeIdList* result;
@end

@implementation DocTypeIdList_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DocTypeIdList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DocTypeIdList_Builder*) clear {
  self.result = [[[DocTypeIdList alloc] init] autorelease];
  return self;
}
- (DocTypeIdList_Builder*) clone {
  return [DocTypeIdList builderWithPrototype:result];
}
- (DocTypeIdList*) defaultInstance {
  return [DocTypeIdList defaultInstance];
}
- (DocTypeIdList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DocTypeIdList*) buildPartial {
  DocTypeIdList* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DocTypeIdList_Builder*) mergeFrom:(DocTypeIdList*) other {
  if (other == [DocTypeIdList defaultInstance]) {
    return self;
  }
  if (other.mutableDocTypeIdList.count > 0) {
    if (result.mutableDocTypeIdList == nil) {
      result.mutableDocTypeIdList = [NSMutableArray array];
    }
    [result.mutableDocTypeIdList addObjectsFromArray:other.mutableDocTypeIdList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DocTypeIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (DocTypeIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self addDocTypeId:[input readString]];
        break;
      }
    }
  }
}
- (NSArray*) docTypeIdList {
  if (result.mutableDocTypeIdList == nil) {
    return [NSArray array];
  }
  return result.mutableDocTypeIdList;
}
- (NSString*) docTypeIdAtIndex:(int32_t) index {
  return [result docTypeIdAtIndex:index];
}
- (DocTypeIdList_Builder*) replaceDocTypeIdAtIndex:(int32_t) index with:(NSString*) value {
  [result.mutableDocTypeIdList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (DocTypeIdList_Builder*) addDocTypeId:(NSString*) value {
  if (result.mutableDocTypeIdList == nil) {
    result.mutableDocTypeIdList = [NSMutableArray array];
  }
  [result.mutableDocTypeIdList addObject:value];
  return self;
}
- (DocTypeIdList_Builder*) addAllDocTypeId:(NSArray*) values {
  if (result.mutableDocTypeIdList == nil) {
    result.mutableDocTypeIdList = [NSMutableArray array];
  }
  [result.mutableDocTypeIdList addObjectsFromArray:values];
  return self;
}
- (DocTypeIdList_Builder*) clearDocTypeIdList {
  result.mutableDocTypeIdList = nil;
  return self;
}
@end

