// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Currency;
@class Currency_Builder;
@class Index;
@class IndexList;
@class IndexList_Builder;
@class Index_Builder;

@interface IndexListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Currency : PBGeneratedMessage {
@private
  BOOL hasCurrency_:1;
  NSString* currency;
}
- (BOOL) hasCurrency;
@property (readonly, retain) NSString* currency;

+ (Currency*) defaultInstance;
- (Currency*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Currency_Builder*) builder;
+ (Currency_Builder*) builder;
+ (Currency_Builder*) builderWithPrototype:(Currency*) prototype;

+ (Currency*) parseFromData:(NSData*) data;
+ (Currency*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Currency*) parseFromInputStream:(NSInputStream*) input;
+ (Currency*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Currency*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Currency*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Currency_Builder : PBGeneratedMessage_Builder {
@private
  Currency* result;
}

- (Currency*) defaultInstance;

- (Currency_Builder*) clear;
- (Currency_Builder*) clone;

- (Currency*) build;
- (Currency*) buildPartial;

- (Currency_Builder*) mergeFrom:(Currency*) other;
- (Currency_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Currency_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCurrency;
- (NSString*) currency;
- (Currency_Builder*) setCurrency:(NSString*) value;
- (Currency_Builder*) clearCurrency;
@end

@interface Index : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasType_:1;
  BOOL hasSuffix_:1;
  BOOL hasPrefix_:1;
  BOOL hasSorting_:1;
  BOOL hasRelatedTo_:1;
  BOOL hasFulltextCreatorId_:1;
  BOOL hasMinLength_:1;
  BOOL hasMaxLength_:1;
  BOOL hasDecimalPrecision_:1;
  BOOL hasMultiple_:1;
  BOOL hasShortcutKey_:1;
  NSString* id;
  NSString* type;
  NSString* suffix;
  NSString* prefix;
  NSString* sorting;
  NSString* relatedTo;
  NSString* fulltextCreatorId;
  NSString* minLength;
  NSString* maxLength;
  NSString* decimalPrecision;
  NSString* multiple;
  NSString* shortcutKey;
  NSMutableArray* mutableUsedCurrenciesList;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasSuffix;
- (BOOL) hasPrefix;
- (BOOL) hasSorting;
- (BOOL) hasRelatedTo;
- (BOOL) hasFulltextCreatorId;
- (BOOL) hasMinLength;
- (BOOL) hasMaxLength;
- (BOOL) hasDecimalPrecision;
- (BOOL) hasMultiple;
- (BOOL) hasShortcutKey;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* type;
@property (readonly, retain) NSString* suffix;
@property (readonly, retain) NSString* prefix;
@property (readonly, retain) NSString* sorting;
@property (readonly, retain) NSString* relatedTo;
@property (readonly, retain) NSString* fulltextCreatorId;
@property (readonly, retain) NSString* minLength;
@property (readonly, retain) NSString* maxLength;
@property (readonly, retain) NSString* decimalPrecision;
@property (readonly, retain) NSString* multiple;
@property (readonly, retain) NSString* shortcutKey;
- (NSArray*) usedCurrenciesList;
- (Currency*) usedCurrenciesAtIndex:(int32_t) index;

+ (Index*) defaultInstance;
- (Index*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Index_Builder*) builder;
+ (Index_Builder*) builder;
+ (Index_Builder*) builderWithPrototype:(Index*) prototype;

+ (Index*) parseFromData:(NSData*) data;
+ (Index*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Index*) parseFromInputStream:(NSInputStream*) input;
+ (Index*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Index*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Index*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Index_Builder : PBGeneratedMessage_Builder {
@private
  Index* result;
}

- (Index*) defaultInstance;

- (Index_Builder*) clear;
- (Index_Builder*) clone;

- (Index*) build;
- (Index*) buildPartial;

- (Index_Builder*) mergeFrom:(Index*) other;
- (Index_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Index_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (Index_Builder*) setId:(NSString*) value;
- (Index_Builder*) clearId;

- (BOOL) hasType;
- (NSString*) type;
- (Index_Builder*) setType:(NSString*) value;
- (Index_Builder*) clearType;

- (BOOL) hasSuffix;
- (NSString*) suffix;
- (Index_Builder*) setSuffix:(NSString*) value;
- (Index_Builder*) clearSuffix;

- (BOOL) hasPrefix;
- (NSString*) prefix;
- (Index_Builder*) setPrefix:(NSString*) value;
- (Index_Builder*) clearPrefix;

- (BOOL) hasSorting;
- (NSString*) sorting;
- (Index_Builder*) setSorting:(NSString*) value;
- (Index_Builder*) clearSorting;

- (BOOL) hasRelatedTo;
- (NSString*) relatedTo;
- (Index_Builder*) setRelatedTo:(NSString*) value;
- (Index_Builder*) clearRelatedTo;

- (BOOL) hasFulltextCreatorId;
- (NSString*) fulltextCreatorId;
- (Index_Builder*) setFulltextCreatorId:(NSString*) value;
- (Index_Builder*) clearFulltextCreatorId;

- (BOOL) hasMinLength;
- (NSString*) minLength;
- (Index_Builder*) setMinLength:(NSString*) value;
- (Index_Builder*) clearMinLength;

- (BOOL) hasMaxLength;
- (NSString*) maxLength;
- (Index_Builder*) setMaxLength:(NSString*) value;
- (Index_Builder*) clearMaxLength;

- (BOOL) hasDecimalPrecision;
- (NSString*) decimalPrecision;
- (Index_Builder*) setDecimalPrecision:(NSString*) value;
- (Index_Builder*) clearDecimalPrecision;

- (BOOL) hasMultiple;
- (NSString*) multiple;
- (Index_Builder*) setMultiple:(NSString*) value;
- (Index_Builder*) clearMultiple;

- (NSArray*) usedCurrenciesList;
- (Currency*) usedCurrenciesAtIndex:(int32_t) index;
- (Index_Builder*) replaceUsedCurrenciesAtIndex:(int32_t) index with:(Currency*) value;
- (Index_Builder*) addUsedCurrencies:(Currency*) value;
- (Index_Builder*) addAllUsedCurrencies:(NSArray*) values;
- (Index_Builder*) clearUsedCurrenciesList;

- (BOOL) hasShortcutKey;
- (NSString*) shortcutKey;
- (Index_Builder*) setShortcutKey:(NSString*) value;
- (Index_Builder*) clearShortcutKey;
@end

@interface IndexList : PBGeneratedMessage {
@private
  NSMutableArray* mutableIndexList;
}
- (NSArray*) indexList;
- (Index*) indexAtIndex:(int32_t) index;

+ (IndexList*) defaultInstance;
- (IndexList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IndexList_Builder*) builder;
+ (IndexList_Builder*) builder;
+ (IndexList_Builder*) builderWithPrototype:(IndexList*) prototype;

+ (IndexList*) parseFromData:(NSData*) data;
+ (IndexList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IndexList*) parseFromInputStream:(NSInputStream*) input;
+ (IndexList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IndexList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IndexList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IndexList_Builder : PBGeneratedMessage_Builder {
@private
  IndexList* result;
}

- (IndexList*) defaultInstance;

- (IndexList_Builder*) clear;
- (IndexList_Builder*) clone;

- (IndexList*) build;
- (IndexList*) buildPartial;

- (IndexList_Builder*) mergeFrom:(IndexList*) other;
- (IndexList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IndexList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) indexList;
- (Index*) indexAtIndex:(int32_t) index;
- (IndexList_Builder*) replaceIndexAtIndex:(int32_t) index with:(Index*) value;
- (IndexList_Builder*) addIndex:(Index*) value;
- (IndexList_Builder*) addAllIndex:(NSArray*) values;
- (IndexList_Builder*) clearIndexList;
@end

