// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MandantCOLLECTION;
@class MandantCOLLECTION_Builder;
@class MandantDefinition;
@class MandantDefinition_Builder;
@class MandantDefinition_Document;
@class MandantDefinition_Document_Builder;
@class MandantDefinition_Page;
@class MandantDefinition_Page_Builder;
@class MandantDefinition_Process;
@class MandantDefinition_Process_Builder;
@class MandantDefinition_WorkBasket;
@class MandantDefinition_WorkBasket_Builder;

@interface MandantCollectionRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MandantDefinition : PBGeneratedMessage {
@private
	BOOL hasAdded_:1;
	BOOL hasId_:1;
	BOOL hasName_:1;
	BOOL hasUrl_:1;
	BOOL hasDescription_:1;
	BOOL added_:1;
	NSString* id;
	NSString* name;
	NSString* url;
	NSString* description;
	NSMutableArray* mutableArrWbsList;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasUrl;
- (BOOL) hasDescription;
- (BOOL) hasAdded;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* url;
@property (readonly, retain) NSString* description;
- (BOOL) added;
- (NSArray*) arrWbsList;
- (MandantDefinition_WorkBasket*) arrWbsAtIndex:(int32_t) index;

+ (MandantDefinition*) defaultInstance;
- (MandantDefinition*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantDefinition_Builder*) builder;
+ (MandantDefinition_Builder*) builder;
+ (MandantDefinition_Builder*) builderWithPrototype:(MandantDefinition*) prototype;

+ (MandantDefinition*) parseFromData:(NSData*) data;
+ (MandantDefinition*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition*) parseFromInputStream:(NSInputStream*) input;
+ (MandantDefinition*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantDefinition*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantDefinition_Page : PBGeneratedMessage {
@private
	BOOL hasReadStatus_:1;
	BOOL hasPageId_:1;
	BOOL hasPageName_:1;
	BOOL hasImgThumnailUrl_:1;
	BOOL hasImgOriginalUrl_:1;
	BOOL readStatus_:1;
	NSString* pageId;
	NSString* pageName;
	NSString* imgThumnailUrl;
	NSString* imgOriginalUrl;
}
- (BOOL) hasPageId;
- (BOOL) hasPageName;
- (BOOL) hasReadStatus;
- (BOOL) hasImgThumnailUrl;
- (BOOL) hasImgOriginalUrl;
@property (readonly, retain) NSString* pageId;
@property (readonly, retain) NSString* pageName;
- (BOOL) readStatus;
@property (readonly, retain) NSString* imgThumnailUrl;
@property (readonly, retain) NSString* imgOriginalUrl;

+ (MandantDefinition_Page*) defaultInstance;
- (MandantDefinition_Page*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantDefinition_Page_Builder*) builder;
+ (MandantDefinition_Page_Builder*) builder;
+ (MandantDefinition_Page_Builder*) builderWithPrototype:(MandantDefinition_Page*) prototype;

+ (MandantDefinition_Page*) parseFromData:(NSData*) data;
+ (MandantDefinition_Page*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_Page*) parseFromInputStream:(NSInputStream*) input;
+ (MandantDefinition_Page*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_Page*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantDefinition_Page*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantDefinition_Page_Builder : PBGeneratedMessage_Builder {
@private
	MandantDefinition_Page* result;
}

- (MandantDefinition_Page*) defaultInstance;

- (MandantDefinition_Page_Builder*) clear;
- (MandantDefinition_Page_Builder*) clone;

- (MandantDefinition_Page*) build;
- (MandantDefinition_Page*) buildPartial;

- (MandantDefinition_Page_Builder*) mergeFrom:(MandantDefinition_Page*) other;
- (MandantDefinition_Page_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantDefinition_Page_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPageId;
- (NSString*) pageId;
- (MandantDefinition_Page_Builder*) setPageId:(NSString*) value;
- (MandantDefinition_Page_Builder*) clearPageId;

- (BOOL) hasPageName;
- (NSString*) pageName;
- (MandantDefinition_Page_Builder*) setPageName:(NSString*) value;
- (MandantDefinition_Page_Builder*) clearPageName;

- (BOOL) hasReadStatus;
- (BOOL) readStatus;
- (MandantDefinition_Page_Builder*) setReadStatus:(BOOL) value;
- (MandantDefinition_Page_Builder*) clearReadStatus;

- (BOOL) hasImgThumnailUrl;
- (NSString*) imgThumnailUrl;
- (MandantDefinition_Page_Builder*) setImgThumnailUrl:(NSString*) value;
- (MandantDefinition_Page_Builder*) clearImgThumnailUrl;

- (BOOL) hasImgOriginalUrl;
- (NSString*) imgOriginalUrl;
- (MandantDefinition_Page_Builder*) setImgOriginalUrl:(NSString*) value;
- (MandantDefinition_Page_Builder*) clearImgOriginalUrl;
@end

@interface MandantDefinition_Document : PBGeneratedMessage {
@private
	BOOL hasNumPages_:1;
	BOOL hasDocId_:1;
	BOOL hasDocName_:1;
	BOOL hasDocUrl_:1;
	BOOL hasDocType_:1;
	BOOL hasDocAmount_:1;
	BOOL hasDocCreditor_:1;
	BOOL hasDocDescription_:1;
	int32_t numPages;
	NSString* docId;
	NSString* docName;
	NSString* docUrl;
	NSString* docType;
	NSString* docAmount;
	NSString* docCreditor;
	NSString* docDescription;
	NSMutableArray* mutableArrPagesList;
}
- (BOOL) hasDocId;
- (BOOL) hasDocName;
- (BOOL) hasDocUrl;
- (BOOL) hasDocType;
- (BOOL) hasNumPages;
- (BOOL) hasDocAmount;
- (BOOL) hasDocCreditor;
- (BOOL) hasDocDescription;
@property (readonly, retain) NSString* docId;
@property (readonly, retain) NSString* docName;
@property (readonly, retain) NSString* docUrl;
@property (readonly, retain) NSString* docType;
@property (readonly) int32_t numPages;
@property (readonly, retain) NSString* docAmount;
@property (readonly, retain) NSString* docCreditor;
@property (readonly, retain) NSString* docDescription;
- (NSArray*) arrPagesList;
- (MandantDefinition_Page*) arrPagesAtIndex:(int32_t) index;

+ (MandantDefinition_Document*) defaultInstance;
- (MandantDefinition_Document*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantDefinition_Document_Builder*) builder;
+ (MandantDefinition_Document_Builder*) builder;
+ (MandantDefinition_Document_Builder*) builderWithPrototype:(MandantDefinition_Document*) prototype;

+ (MandantDefinition_Document*) parseFromData:(NSData*) data;
+ (MandantDefinition_Document*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_Document*) parseFromInputStream:(NSInputStream*) input;
+ (MandantDefinition_Document*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_Document*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantDefinition_Document*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantDefinition_Document_Builder : PBGeneratedMessage_Builder {
@private
	MandantDefinition_Document* result;
}

- (MandantDefinition_Document*) defaultInstance;

- (MandantDefinition_Document_Builder*) clear;
- (MandantDefinition_Document_Builder*) clone;

- (MandantDefinition_Document*) build;
- (MandantDefinition_Document*) buildPartial;

- (MandantDefinition_Document_Builder*) mergeFrom:(MandantDefinition_Document*) other;
- (MandantDefinition_Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantDefinition_Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDocId;
- (NSString*) docId;
- (MandantDefinition_Document_Builder*) setDocId:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocId;

- (BOOL) hasDocName;
- (NSString*) docName;
- (MandantDefinition_Document_Builder*) setDocName:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocName;

- (BOOL) hasDocUrl;
- (NSString*) docUrl;
- (MandantDefinition_Document_Builder*) setDocUrl:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocUrl;

- (BOOL) hasDocType;
- (NSString*) docType;
- (MandantDefinition_Document_Builder*) setDocType:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocType;

- (BOOL) hasNumPages;
- (int32_t) numPages;
- (MandantDefinition_Document_Builder*) setNumPages:(int32_t) value;
- (MandantDefinition_Document_Builder*) clearNumPages;

- (BOOL) hasDocAmount;
- (NSString*) docAmount;
- (MandantDefinition_Document_Builder*) setDocAmount:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocAmount;

- (BOOL) hasDocCreditor;
- (NSString*) docCreditor;
- (MandantDefinition_Document_Builder*) setDocCreditor:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocCreditor;

- (BOOL) hasDocDescription;
- (NSString*) docDescription;
- (MandantDefinition_Document_Builder*) setDocDescription:(NSString*) value;
- (MandantDefinition_Document_Builder*) clearDocDescription;

- (NSArray*) arrPagesList;
- (MandantDefinition_Page*) arrPagesAtIndex:(int32_t) index;
- (MandantDefinition_Document_Builder*) replaceArrPagesAtIndex:(int32_t) index with:(MandantDefinition_Page*) value;
- (MandantDefinition_Document_Builder*) addArrPages:(MandantDefinition_Page*) value;
- (MandantDefinition_Document_Builder*) addAllArrPages:(NSArray*) values;
- (MandantDefinition_Document_Builder*) clearArrPagesList;
@end

@interface MandantDefinition_Process : PBGeneratedMessage {
@private
	BOOL hasReadStatus_:1;
	BOOL hasNumDocs_:1;
	BOOL hasProId_:1;
	BOOL hasProName_:1;
	BOOL hasProUrl_:1;
	BOOL hasProDescription_:1;
	BOOL hasProEntryDate_:1;
	BOOL hasProType_:1;
	BOOL readStatus_:1;
	int32_t numDocs;
	NSString* proId;
	NSString* proName;
	NSString* proUrl;
	NSString* proDescription;
	NSString* proEntryDate;
	NSString* proType;
	NSMutableArray* mutableArrDocsList;
}
- (BOOL) hasProId;
- (BOOL) hasProName;
- (BOOL) hasProUrl;
- (BOOL) hasProDescription;
- (BOOL) hasReadStatus;
- (BOOL) hasNumDocs;
- (BOOL) hasProEntryDate;
- (BOOL) hasProType;
@property (readonly, retain) NSString* proId;
@property (readonly, retain) NSString* proName;
@property (readonly, retain) NSString* proUrl;
@property (readonly, retain) NSString* proDescription;
- (BOOL) readStatus;
@property (readonly) int32_t numDocs;
@property (readonly, retain) NSString* proEntryDate;
@property (readonly, retain) NSString* proType;
- (NSArray*) arrDocsList;
- (MandantDefinition_Document*) arrDocsAtIndex:(int32_t) index;

+ (MandantDefinition_Process*) defaultInstance;
- (MandantDefinition_Process*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantDefinition_Process_Builder*) builder;
+ (MandantDefinition_Process_Builder*) builder;
+ (MandantDefinition_Process_Builder*) builderWithPrototype:(MandantDefinition_Process*) prototype;

+ (MandantDefinition_Process*) parseFromData:(NSData*) data;
+ (MandantDefinition_Process*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_Process*) parseFromInputStream:(NSInputStream*) input;
+ (MandantDefinition_Process*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_Process*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantDefinition_Process*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantDefinition_Process_Builder : PBGeneratedMessage_Builder {
@private
	MandantDefinition_Process* result;
}

- (MandantDefinition_Process*) defaultInstance;

- (MandantDefinition_Process_Builder*) clear;
- (MandantDefinition_Process_Builder*) clone;

- (MandantDefinition_Process*) build;
- (MandantDefinition_Process*) buildPartial;

- (MandantDefinition_Process_Builder*) mergeFrom:(MandantDefinition_Process*) other;
- (MandantDefinition_Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantDefinition_Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProId;
- (NSString*) proId;
- (MandantDefinition_Process_Builder*) setProId:(NSString*) value;
- (MandantDefinition_Process_Builder*) clearProId;

- (BOOL) hasProName;
- (NSString*) proName;
- (MandantDefinition_Process_Builder*) setProName:(NSString*) value;
- (MandantDefinition_Process_Builder*) clearProName;

- (BOOL) hasProUrl;
- (NSString*) proUrl;
- (MandantDefinition_Process_Builder*) setProUrl:(NSString*) value;
- (MandantDefinition_Process_Builder*) clearProUrl;

- (BOOL) hasProDescription;
- (NSString*) proDescription;
- (MandantDefinition_Process_Builder*) setProDescription:(NSString*) value;
- (MandantDefinition_Process_Builder*) clearProDescription;

- (BOOL) hasReadStatus;
- (BOOL) readStatus;
- (MandantDefinition_Process_Builder*) setReadStatus:(BOOL) value;
- (MandantDefinition_Process_Builder*) clearReadStatus;

- (BOOL) hasNumDocs;
- (int32_t) numDocs;
- (MandantDefinition_Process_Builder*) setNumDocs:(int32_t) value;
- (MandantDefinition_Process_Builder*) clearNumDocs;

- (BOOL) hasProEntryDate;
- (NSString*) proEntryDate;
- (MandantDefinition_Process_Builder*) setProEntryDate:(NSString*) value;
- (MandantDefinition_Process_Builder*) clearProEntryDate;

- (BOOL) hasProType;
- (NSString*) proType;
- (MandantDefinition_Process_Builder*) setProType:(NSString*) value;
- (MandantDefinition_Process_Builder*) clearProType;

- (NSArray*) arrDocsList;
- (MandantDefinition_Document*) arrDocsAtIndex:(int32_t) index;
- (MandantDefinition_Process_Builder*) replaceArrDocsAtIndex:(int32_t) index with:(MandantDefinition_Document*) value;
- (MandantDefinition_Process_Builder*) addArrDocs:(MandantDefinition_Document*) value;
- (MandantDefinition_Process_Builder*) addAllArrDocs:(NSArray*) values;
- (MandantDefinition_Process_Builder*) clearArrDocsList;
@end

@interface MandantDefinition_WorkBasket : PBGeneratedMessage {
@private
	BOOL hasWbId_:1;
	BOOL hasWbName_:1;
	BOOL hasWbUrl_:1;
	BOOL hasGroupname_:1;
	BOOL hasWbDescription_:1;
	BOOL hasLastBuildDate_:1;
	NSString* wbId;
	NSString* wbName;
	NSString* wbUrl;
	NSString* groupname;
	NSString* wbDescription;
	NSString* lastBuildDate;
	NSMutableArray* mutableArrProsList;
}
- (BOOL) hasWbId;
- (BOOL) hasWbName;
- (BOOL) hasWbUrl;
- (BOOL) hasGroupname;
- (BOOL) hasWbDescription;
- (BOOL) hasLastBuildDate;
@property (readonly, retain) NSString* wbId;
@property (readonly, retain) NSString* wbName;
@property (readonly, retain) NSString* wbUrl;
@property (readonly, retain) NSString* groupname;
@property (readonly, retain) NSString* wbDescription;
@property (readonly, retain) NSString* lastBuildDate;
- (NSArray*) arrProsList;
- (MandantDefinition_Process*) arrProsAtIndex:(int32_t) index;

+ (MandantDefinition_WorkBasket*) defaultInstance;
- (MandantDefinition_WorkBasket*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantDefinition_WorkBasket_Builder*) builder;
+ (MandantDefinition_WorkBasket_Builder*) builder;
+ (MandantDefinition_WorkBasket_Builder*) builderWithPrototype:(MandantDefinition_WorkBasket*) prototype;

+ (MandantDefinition_WorkBasket*) parseFromData:(NSData*) data;
+ (MandantDefinition_WorkBasket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_WorkBasket*) parseFromInputStream:(NSInputStream*) input;
+ (MandantDefinition_WorkBasket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantDefinition_WorkBasket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantDefinition_WorkBasket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantDefinition_WorkBasket_Builder : PBGeneratedMessage_Builder {
@private
	MandantDefinition_WorkBasket* result;
}

- (MandantDefinition_WorkBasket*) defaultInstance;

- (MandantDefinition_WorkBasket_Builder*) clear;
- (MandantDefinition_WorkBasket_Builder*) clone;

- (MandantDefinition_WorkBasket*) build;
- (MandantDefinition_WorkBasket*) buildPartial;

- (MandantDefinition_WorkBasket_Builder*) mergeFrom:(MandantDefinition_WorkBasket*) other;
- (MandantDefinition_WorkBasket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantDefinition_WorkBasket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasWbId;
- (NSString*) wbId;
- (MandantDefinition_WorkBasket_Builder*) setWbId:(NSString*) value;
- (MandantDefinition_WorkBasket_Builder*) clearWbId;

- (BOOL) hasWbName;
- (NSString*) wbName;
- (MandantDefinition_WorkBasket_Builder*) setWbName:(NSString*) value;
- (MandantDefinition_WorkBasket_Builder*) clearWbName;

- (BOOL) hasWbUrl;
- (NSString*) wbUrl;
- (MandantDefinition_WorkBasket_Builder*) setWbUrl:(NSString*) value;
- (MandantDefinition_WorkBasket_Builder*) clearWbUrl;

- (BOOL) hasGroupname;
- (NSString*) groupname;
- (MandantDefinition_WorkBasket_Builder*) setGroupname:(NSString*) value;
- (MandantDefinition_WorkBasket_Builder*) clearGroupname;

- (BOOL) hasWbDescription;
- (NSString*) wbDescription;
- (MandantDefinition_WorkBasket_Builder*) setWbDescription:(NSString*) value;
- (MandantDefinition_WorkBasket_Builder*) clearWbDescription;

- (BOOL) hasLastBuildDate;
- (NSString*) lastBuildDate;
- (MandantDefinition_WorkBasket_Builder*) setLastBuildDate:(NSString*) value;
- (MandantDefinition_WorkBasket_Builder*) clearLastBuildDate;

- (NSArray*) arrProsList;
- (MandantDefinition_Process*) arrProsAtIndex:(int32_t) index;
- (MandantDefinition_WorkBasket_Builder*) replaceArrProsAtIndex:(int32_t) index with:(MandantDefinition_Process*) value;
- (MandantDefinition_WorkBasket_Builder*) addArrPros:(MandantDefinition_Process*) value;
- (MandantDefinition_WorkBasket_Builder*) addAllArrPros:(NSArray*) values;
- (MandantDefinition_WorkBasket_Builder*) clearArrProsList;
@end

@interface MandantDefinition_Builder : PBGeneratedMessage_Builder {
@private
	MandantDefinition* result;
}

- (MandantDefinition*) defaultInstance;

- (MandantDefinition_Builder*) clear;
- (MandantDefinition_Builder*) clone;

- (MandantDefinition*) build;
- (MandantDefinition*) buildPartial;

- (MandantDefinition_Builder*) mergeFrom:(MandantDefinition*) other;
- (MandantDefinition_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantDefinition_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MandantDefinition_Builder*) setId:(NSString*) value;
- (MandantDefinition_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (MandantDefinition_Builder*) setName:(NSString*) value;
- (MandantDefinition_Builder*) clearName;

- (BOOL) hasUrl;
- (NSString*) url;
- (MandantDefinition_Builder*) setUrl:(NSString*) value;
- (MandantDefinition_Builder*) clearUrl;

- (BOOL) hasDescription;
- (NSString*) description;
- (MandantDefinition_Builder*) setDescription:(NSString*) value;
- (MandantDefinition_Builder*) clearDescription;

- (BOOL) hasAdded;
- (BOOL) added;
- (MandantDefinition_Builder*) setAdded:(BOOL) value;
- (MandantDefinition_Builder*) clearAdded;

- (NSArray*) arrWbsList;
- (MandantDefinition_WorkBasket*) arrWbsAtIndex:(int32_t) index;
- (MandantDefinition_Builder*) replaceArrWbsAtIndex:(int32_t) index with:(MandantDefinition_WorkBasket*) value;
- (MandantDefinition_Builder*) addArrWbs:(MandantDefinition_WorkBasket*) value;
- (MandantDefinition_Builder*) addAllArrWbs:(NSArray*) values;
- (MandantDefinition_Builder*) clearArrWbsList;
@end

@interface MandantCOLLECTION : PBGeneratedMessage {
@private
	NSMutableArray* mutableMandantList;
}
- (NSArray*) mandantList;
- (MandantDefinition*) mandantAtIndex:(int32_t) index;

+ (MandantCOLLECTION*) defaultInstance;
- (MandantCOLLECTION*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantCOLLECTION_Builder*) builder;
+ (MandantCOLLECTION_Builder*) builder;
+ (MandantCOLLECTION_Builder*) builderWithPrototype:(MandantCOLLECTION*) prototype;

+ (MandantCOLLECTION*) parseFromData:(NSData*) data;
+ (MandantCOLLECTION*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantCOLLECTION*) parseFromInputStream:(NSInputStream*) input;
+ (MandantCOLLECTION*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantCOLLECTION*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantCOLLECTION*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantCOLLECTION_Builder : PBGeneratedMessage_Builder {
@private
	MandantCOLLECTION* result;
}

- (MandantCOLLECTION*) defaultInstance;

- (MandantCOLLECTION_Builder*) clear;
- (MandantCOLLECTION_Builder*) clone;

- (MandantCOLLECTION*) build;
- (MandantCOLLECTION*) buildPartial;

- (MandantCOLLECTION_Builder*) mergeFrom:(MandantCOLLECTION*) other;
- (MandantCOLLECTION_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantCOLLECTION_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) mandantList;
- (MandantDefinition*) mandantAtIndex:(int32_t) index;
- (MandantCOLLECTION_Builder*) replaceMandantAtIndex:(int32_t) index with:(MandantDefinition*) value;
- (MandantCOLLECTION_Builder*) addMandant:(MandantDefinition*) value;
- (MandantCOLLECTION_Builder*) addAllMandant:(NSArray*) values;
- (MandantCOLLECTION_Builder*) clearMandantList;
@end

