// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Command;
@class CommandList;
@class CommandList_Builder;
@class Command_Builder;

@interface CommandListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Command : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  NSString* id;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;

+ (Command*) defaultInstance;
- (Command*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Command_Builder*) builder;
+ (Command_Builder*) builder;
+ (Command_Builder*) builderWithPrototype:(Command*) prototype;

+ (Command*) parseFromData:(NSData*) data;
+ (Command*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Command*) parseFromInputStream:(NSInputStream*) input;
+ (Command*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Command*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Command*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Command_Builder : PBGeneratedMessage_Builder {
@private
  Command* result;
}

- (Command*) defaultInstance;

- (Command_Builder*) clear;
- (Command_Builder*) clone;

- (Command*) build;
- (Command*) buildPartial;

- (Command_Builder*) mergeFrom:(Command*) other;
- (Command_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Command_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (Command_Builder*) setId:(NSString*) value;
- (Command_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (Command_Builder*) setName:(NSString*) value;
- (Command_Builder*) clearName;
@end

@interface CommandList : PBGeneratedMessage {
@private
  NSMutableArray* mutableCommandList;
}
- (NSArray*) commandList;
- (Command*) commandAtIndex:(int32_t) index;

+ (CommandList*) defaultInstance;
- (CommandList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CommandList_Builder*) builder;
+ (CommandList_Builder*) builder;
+ (CommandList_Builder*) builderWithPrototype:(CommandList*) prototype;

+ (CommandList*) parseFromData:(NSData*) data;
+ (CommandList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommandList*) parseFromInputStream:(NSInputStream*) input;
+ (CommandList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommandList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CommandList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CommandList_Builder : PBGeneratedMessage_Builder {
@private
  CommandList* result;
}

- (CommandList*) defaultInstance;

- (CommandList_Builder*) clear;
- (CommandList_Builder*) clone;

- (CommandList*) build;
- (CommandList*) buildPartial;

- (CommandList_Builder*) mergeFrom:(CommandList*) other;
- (CommandList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CommandList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) commandList;
- (Command*) commandAtIndex:(int32_t) index;
- (CommandList_Builder*) replaceCommandAtIndex:(int32_t) index with:(Command*) value;
- (CommandList_Builder*) addCommand:(Command*) value;
- (CommandList_Builder*) addAllCommand:(NSArray*) values;
- (CommandList_Builder*) clearCommandList;
@end

