// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class DocTypeIdList;
@class DocTypeIdList_Builder;

@interface DocTypeIdListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface DocTypeIdList : PBGeneratedMessage {
@private
  NSMutableArray* mutableDocTypeIdList;
}
- (NSArray*) docTypeIdList;
- (NSString*) docTypeIdAtIndex:(int32_t) index;

+ (DocTypeIdList*) defaultInstance;
- (DocTypeIdList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DocTypeIdList_Builder*) builder;
+ (DocTypeIdList_Builder*) builder;
+ (DocTypeIdList_Builder*) builderWithPrototype:(DocTypeIdList*) prototype;

+ (DocTypeIdList*) parseFromData:(NSData*) data;
+ (DocTypeIdList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DocTypeIdList*) parseFromInputStream:(NSInputStream*) input;
+ (DocTypeIdList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DocTypeIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DocTypeIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DocTypeIdList_Builder : PBGeneratedMessage_Builder {
@private
  DocTypeIdList* result;
}

- (DocTypeIdList*) defaultInstance;

- (DocTypeIdList_Builder*) clear;
- (DocTypeIdList_Builder*) clone;

- (DocTypeIdList*) build;
- (DocTypeIdList*) buildPartial;

- (DocTypeIdList_Builder*) mergeFrom:(DocTypeIdList*) other;
- (DocTypeIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DocTypeIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) docTypeIdList;
- (NSString*) docTypeIdAtIndex:(int32_t) index;
- (DocTypeIdList_Builder*) replaceDocTypeIdAtIndex:(int32_t) index with:(NSString*) value;
- (DocTypeIdList_Builder*) addDocTypeId:(NSString*) value;
- (DocTypeIdList_Builder*) addAllDocTypeId:(NSArray*) values;
- (DocTypeIdList_Builder*) clearDocTypeIdList;
@end

