// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Mandant;
@class MandantList;
@class MandantList_Builder;
@class Mandant_Builder;

@interface MandantListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Mandant : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  NSString* id;
  NSString* name;
  BOOL isAdded;
  //NSMutableArray *arrWb;
}
- (BOOL) hasId;
- (BOOL) hasName;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;
@property BOOL isAdded;
//@property (retain) NSMutableArray *arrWb;

+ (Mandant*) defaultInstance;
- (Mandant*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Mandant_Builder*) builder;
+ (Mandant_Builder*) builder;
+ (Mandant_Builder*) builderWithPrototype:(Mandant*) prototype;

+ (Mandant*) parseFromData:(NSData*) data;
+ (Mandant*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Mandant*) parseFromInputStream:(NSInputStream*) input;
+ (Mandant*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Mandant*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Mandant*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Mandant_Builder : PBGeneratedMessage_Builder {
@private
  Mandant* result;
}

- (Mandant*) defaultInstance;

- (Mandant_Builder*) clear;
- (Mandant_Builder*) clone;

- (Mandant*) build;
- (Mandant*) buildPartial;

- (Mandant_Builder*) mergeFrom:(Mandant*) other;
- (Mandant_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Mandant_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (Mandant_Builder*) setId:(NSString*) value;
- (Mandant_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (Mandant_Builder*) setName:(NSString*) value;
- (Mandant_Builder*) clearName;
@end

@interface MandantList : PBGeneratedMessage {
@private
  NSMutableArray* mutableMandantList;
}
- (NSArray*) mandantList;
- (Mandant*) mandantAtIndex:(int32_t) index;

+ (MandantList*) defaultInstance;
- (MandantList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MandantList_Builder*) builder;
+ (MandantList_Builder*) builder;
+ (MandantList_Builder*) builderWithPrototype:(MandantList*) prototype;

+ (MandantList*) parseFromData:(NSData*) data;
+ (MandantList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantList*) parseFromInputStream:(NSInputStream*) input;
+ (MandantList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MandantList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MandantList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MandantList_Builder : PBGeneratedMessage_Builder {
@private
  MandantList* result;
}

- (MandantList*) defaultInstance;

- (MandantList_Builder*) clear;
- (MandantList_Builder*) clone;

- (MandantList*) build;
- (MandantList*) buildPartial;

- (MandantList_Builder*) mergeFrom:(MandantList*) other;
- (MandantList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MandantList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) mandantList;
- (Mandant*) mandantAtIndex:(int32_t) index;
- (MandantList_Builder*) replaceMandantAtIndex:(int32_t) index with:(Mandant*) value;
- (MandantList_Builder*) addMandant:(Mandant*) value;
- (MandantList_Builder*) addAllMandant:(NSArray*) values;
- (MandantList_Builder*) clearMandantList;
@end

