// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "MandantCollection.pb.h"

@implementation MandantCollectionRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
	return extensionRegistry;
}

+ (void) initialize {
	if (self == [MandantCollectionRoot class]) {
		PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
		[self registerAllExtensions:registry];
		extensionRegistry = [registry retain];
	}
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface MandantDefinition ()
@property (retain) NSString* id;
@property (retain) NSString* name;
@property (retain) NSString* url;
@property (retain) NSString* description;
@property BOOL added;
@property (retain) NSMutableArray* mutableArrWbsList;
@end

@implementation MandantDefinition

- (BOOL) hasId {
	return !!hasId_;
}
- (void) setHasId:(BOOL) value {
	hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasName {
	return !!hasName_;
}
- (void) setHasName:(BOOL) value {
	hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasUrl {
	return !!hasUrl_;
}
- (void) setHasUrl:(BOOL) value {
	hasUrl_ = !!value;
}
@synthesize url;
- (BOOL) hasDescription {
	return !!hasDescription_;
}
- (void) setHasDescription:(BOOL) value {
	hasDescription_ = !!value;
}
@synthesize description;
- (BOOL) hasAdded {
	return !!hasAdded_;
}
- (void) setHasAdded:(BOOL) value {
	hasAdded_ = !!value;
}
- (BOOL) added {
	return !!added_;
}
- (void) setAdded:(BOOL) value {
	added_ = !!value;
}
@synthesize mutableArrWbsList;
- (void) dealloc {
	self.id = nil;
	self.name = nil;
	self.url = nil;
	self.description = nil;
	self.mutableArrWbsList = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.id = @"";
		self.name = @"";
		self.url = @"";
		self.description = @"";
		self.added = NO;
	}
	return self;
}
static MandantDefinition* defaultMandantDefinitionInstance = nil;
+ (void) initialize {
	if (self == [MandantDefinition class]) {
		defaultMandantDefinitionInstance = [[MandantDefinition alloc] init];
	}
}
+ (MandantDefinition*) defaultInstance {
	return defaultMandantDefinitionInstance;
}
- (MandantDefinition*) defaultInstance {
	return defaultMandantDefinitionInstance;
}
- (NSArray*) arrWbsList {
	return mutableArrWbsList;
}
- (MandantDefinition_WorkBasket*) arrWbsAtIndex:(int32_t) index {
	id value = [mutableArrWbsList objectAtIndex:index];
	return value;
}
- (BOOL) isInitialized {
	return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
	if (self.hasId) {
		[output writeString:1 value:self.id];
	}
	if (self.hasName) {
		[output writeString:2 value:self.name];
	}
	if (self.hasUrl) {
		[output writeString:3 value:self.url];
	}
	if (self.hasDescription) {
		[output writeString:4 value:self.description];
	}
	if (self.hasAdded) {
		[output writeBool:5 value:self.added];
	}
	for (MandantDefinition_WorkBasket* element in self.arrWbsList) {
		[output writeMessage:6 value:element];
	}
	[self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
	int32_t size = memoizedSerializedSize;
	if (size != -1) {
		return size;
	}
	
	size = 0;
	if (self.hasId) {
		size += computeStringSize(1, self.id);
	}
	if (self.hasName) {
		size += computeStringSize(2, self.name);
	}
	if (self.hasUrl) {
		size += computeStringSize(3, self.url);
	}
	if (self.hasDescription) {
		size += computeStringSize(4, self.description);
	}
	if (self.hasAdded) {
		size += computeBoolSize(5, self.added);
	}
	for (MandantDefinition_WorkBasket* element in self.arrWbsList) {
		size += computeMessageSize(6, element);
	}
	size += self.unknownFields.serializedSize;
	memoizedSerializedSize = size;
	return size;
}
+ (MandantDefinition*) parseFromData:(NSData*) data {
	return (MandantDefinition*)[[[MandantDefinition builder] mergeFromData:data] build];
}
+ (MandantDefinition*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition*)[[[MandantDefinition builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition*) parseFromInputStream:(NSInputStream*) input {
	return (MandantDefinition*)[[[MandantDefinition builder] mergeFromInputStream:input] build];
}
+ (MandantDefinition*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition*)[[[MandantDefinition builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition*) parseFromCodedInputStream:(PBCodedInputStream*) input {
	return (MandantDefinition*)[[[MandantDefinition builder] mergeFromCodedInputStream:input] build];
}
+ (MandantDefinition*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition*)[[[MandantDefinition builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Builder*) builder {
	return [[[MandantDefinition_Builder alloc] init] autorelease];
}
+ (MandantDefinition_Builder*) builderWithPrototype:(MandantDefinition*) prototype {
	return [[MandantDefinition builder] mergeFrom:prototype];
}
- (MandantDefinition_Builder*) builder {
	return [MandantDefinition builder];
}
@end

@interface MandantDefinition_Page ()
@property (retain) NSString* pageId;
@property (retain) NSString* pageName;
@property BOOL readStatus;
@property (retain) NSString* imgThumnailUrl;
@property (retain) NSString* imgOriginalUrl;
@end

@implementation MandantDefinition_Page

- (BOOL) hasPageId {
	return !!hasPageId_;
}
- (void) setHasPageId:(BOOL) value {
	hasPageId_ = !!value;
}
@synthesize pageId;
- (BOOL) hasPageName {
	return !!hasPageName_;
}
- (void) setHasPageName:(BOOL) value {
	hasPageName_ = !!value;
}
@synthesize pageName;
- (BOOL) hasReadStatus {
	return !!hasReadStatus_;
}
- (void) setHasReadStatus:(BOOL) value {
	hasReadStatus_ = !!value;
}
- (BOOL) readStatus {
	return !!readStatus_;
}
- (void) setReadStatus:(BOOL) value {
	readStatus_ = !!value;
}
- (BOOL) hasImgThumnailUrl {
	return !!hasImgThumnailUrl_;
}
- (void) setHasImgThumnailUrl:(BOOL) value {
	hasImgThumnailUrl_ = !!value;
}
@synthesize imgThumnailUrl;
- (BOOL) hasImgOriginalUrl {
	return !!hasImgOriginalUrl_;
}
- (void) setHasImgOriginalUrl:(BOOL) value {
	hasImgOriginalUrl_ = !!value;
}
@synthesize imgOriginalUrl;
- (void) dealloc {
	self.pageId = nil;
	self.pageName = nil;
	self.imgThumnailUrl = nil;
	self.imgOriginalUrl = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.pageId = @"";
		self.pageName = @"";
		self.readStatus = NO;
		self.imgThumnailUrl = @"";
		self.imgOriginalUrl = @"";
	}
	return self;
}
static MandantDefinition_Page* defaultMandantDefinition_PageInstance = nil;
+ (void) initialize {
	if (self == [MandantDefinition_Page class]) {
		defaultMandantDefinition_PageInstance = [[MandantDefinition_Page alloc] init];
	}
}
+ (MandantDefinition_Page*) defaultInstance {
	return defaultMandantDefinition_PageInstance;
}
- (MandantDefinition_Page*) defaultInstance {
	return defaultMandantDefinition_PageInstance;
}
- (BOOL) isInitialized {
	return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
	if (self.hasPageId) {
		[output writeString:1 value:self.pageId];
	}
	if (self.hasPageName) {
		[output writeString:2 value:self.pageName];
	}
	if (self.hasReadStatus) {
		[output writeBool:3 value:self.readStatus];
	}
	if (self.hasImgThumnailUrl) {
		[output writeString:4 value:self.imgThumnailUrl];
	}
	if (self.hasImgOriginalUrl) {
		[output writeString:5 value:self.imgOriginalUrl];
	}
	[self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
	int32_t size = memoizedSerializedSize;
	if (size != -1) {
		return size;
	}
	
	size = 0;
	if (self.hasPageId) {
		size += computeStringSize(1, self.pageId);
	}
	if (self.hasPageName) {
		size += computeStringSize(2, self.pageName);
	}
	if (self.hasReadStatus) {
		size += computeBoolSize(3, self.readStatus);
	}
	if (self.hasImgThumnailUrl) {
		size += computeStringSize(4, self.imgThumnailUrl);
	}
	if (self.hasImgOriginalUrl) {
		size += computeStringSize(5, self.imgOriginalUrl);
	}
	size += self.unknownFields.serializedSize;
	memoizedSerializedSize = size;
	return size;
}
+ (MandantDefinition_Page*) parseFromData:(NSData*) data {
	return (MandantDefinition_Page*)[[[MandantDefinition_Page builder] mergeFromData:data] build];
}
+ (MandantDefinition_Page*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Page*)[[[MandantDefinition_Page builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Page*) parseFromInputStream:(NSInputStream*) input {
	return (MandantDefinition_Page*)[[[MandantDefinition_Page builder] mergeFromInputStream:input] build];
}
+ (MandantDefinition_Page*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Page*)[[[MandantDefinition_Page builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Page*) parseFromCodedInputStream:(PBCodedInputStream*) input {
	return (MandantDefinition_Page*)[[[MandantDefinition_Page builder] mergeFromCodedInputStream:input] build];
}
+ (MandantDefinition_Page*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Page*)[[[MandantDefinition_Page builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Page_Builder*) builder {
	return [[[MandantDefinition_Page_Builder alloc] init] autorelease];
}
+ (MandantDefinition_Page_Builder*) builderWithPrototype:(MandantDefinition_Page*) prototype {
	return [[MandantDefinition_Page builder] mergeFrom:prototype];
}
- (MandantDefinition_Page_Builder*) builder {
	return [MandantDefinition_Page builder];
}
@end

@interface MandantDefinition_Page_Builder()
@property (retain) MandantDefinition_Page* result;
@end

@implementation MandantDefinition_Page_Builder
@synthesize result;
- (void) dealloc {
	self.result = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.result = [[[MandantDefinition_Page alloc] init] autorelease];
	}
	return self;
}
- (PBGeneratedMessage*) internalGetResult {
	return result;
}
- (MandantDefinition_Page_Builder*) clear {
	self.result = [[[MandantDefinition_Page alloc] init] autorelease];
	return self;
}
- (MandantDefinition_Page_Builder*) clone {
	return [MandantDefinition_Page builderWithPrototype:result];
}
- (MandantDefinition_Page*) defaultInstance {
	return [MandantDefinition_Page defaultInstance];
}
- (MandantDefinition_Page*) build {
	[self checkInitialized];
	return [self buildPartial];
}
- (MandantDefinition_Page*) buildPartial {
	MandantDefinition_Page* returnMe = [[result retain] autorelease];
	self.result = nil;
	return returnMe;
}
- (MandantDefinition_Page_Builder*) mergeFrom:(MandantDefinition_Page*) other {
	if (other == [MandantDefinition_Page defaultInstance]) {
		return self;
	}
	if (other.hasPageId) {
		[self setPageId:other.pageId];
	}
	if (other.hasPageName) {
		[self setPageName:other.pageName];
	}
	if (other.hasReadStatus) {
		[self setReadStatus:other.readStatus];
	}
	if (other.hasImgThumnailUrl) {
		[self setImgThumnailUrl:other.imgThumnailUrl];
	}
	if (other.hasImgOriginalUrl) {
		[self setImgOriginalUrl:other.imgOriginalUrl];
	}
	[self mergeUnknownFields:other.unknownFields];
	return self;
}
- (MandantDefinition_Page_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
	return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MandantDefinition_Page_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
	while (YES) {
		int32_t tag = [input readTag];
		switch (tag) {
			case 0:
				[self setUnknownFields:[unknownFields build]];
				return self;
			default: {
				if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
					[self setUnknownFields:[unknownFields build]];
					return self;
				}
				break;
			}
			case 10: {
				[self setPageId:[input readString]];
				break;
			}
			case 18: {
				[self setPageName:[input readString]];
				break;
			}
			case 24: {
				[self setReadStatus:[input readBool]];
				break;
			}
			case 34: {
				[self setImgThumnailUrl:[input readString]];
				break;
			}
			case 42: {
				[self setImgOriginalUrl:[input readString]];
				break;
			}
		}
	}
}
- (BOOL) hasPageId {
	return result.hasPageId;
}
- (NSString*) pageId {
	return result.pageId;
}
- (MandantDefinition_Page_Builder*) setPageId:(NSString*) value {
	result.hasPageId = YES;
	result.pageId = value;
	return self;
}
- (MandantDefinition_Page_Builder*) clearPageId {
	result.hasPageId = NO;
	result.pageId = @"";
	return self;
}
- (BOOL) hasPageName {
	return result.hasPageName;
}
- (NSString*) pageName {
	return result.pageName;
}
- (MandantDefinition_Page_Builder*) setPageName:(NSString*) value {
	result.hasPageName = YES;
	result.pageName = value;
	return self;
}
- (MandantDefinition_Page_Builder*) clearPageName {
	result.hasPageName = NO;
	result.pageName = @"";
	return self;
}
- (BOOL) hasReadStatus {
	return result.hasReadStatus;
}
- (BOOL) readStatus {
	return result.readStatus;
}
- (MandantDefinition_Page_Builder*) setReadStatus:(BOOL) value {
	result.hasReadStatus = YES;
	result.readStatus = value;
	return self;
}
- (MandantDefinition_Page_Builder*) clearReadStatus {
	result.hasReadStatus = NO;
	result.readStatus = NO;
	return self;
}
- (BOOL) hasImgThumnailUrl {
	return result.hasImgThumnailUrl;
}
- (NSString*) imgThumnailUrl {
	return result.imgThumnailUrl;
}
- (MandantDefinition_Page_Builder*) setImgThumnailUrl:(NSString*) value {
	result.hasImgThumnailUrl = YES;
	result.imgThumnailUrl = value;
	return self;
}
- (MandantDefinition_Page_Builder*) clearImgThumnailUrl {
	result.hasImgThumnailUrl = NO;
	result.imgThumnailUrl = @"";
	return self;
}
- (BOOL) hasImgOriginalUrl {
	return result.hasImgOriginalUrl;
}
- (NSString*) imgOriginalUrl {
	return result.imgOriginalUrl;
}
- (MandantDefinition_Page_Builder*) setImgOriginalUrl:(NSString*) value {
	result.hasImgOriginalUrl = YES;
	result.imgOriginalUrl = value;
	return self;
}
- (MandantDefinition_Page_Builder*) clearImgOriginalUrl {
	result.hasImgOriginalUrl = NO;
	result.imgOriginalUrl = @"";
	return self;
}
@end

@interface MandantDefinition_Document ()
@property (retain) NSString* docId;
@property (retain) NSString* docName;
@property (retain) NSString* docUrl;
@property (retain) NSString* docType;
@property int32_t numPages;
@property (retain) NSString* docAmount;
@property (retain) NSString* docCreditor;
@property (retain) NSString* docDescription;
@property (retain) NSMutableArray* mutableArrPagesList;
@end

@implementation MandantDefinition_Document

- (BOOL) hasDocId {
	return !!hasDocId_;
}
- (void) setHasDocId:(BOOL) value {
	hasDocId_ = !!value;
}
@synthesize docId;
- (BOOL) hasDocName {
	return !!hasDocName_;
}
- (void) setHasDocName:(BOOL) value {
	hasDocName_ = !!value;
}
@synthesize docName;
- (BOOL) hasDocUrl {
	return !!hasDocUrl_;
}
- (void) setHasDocUrl:(BOOL) value {
	hasDocUrl_ = !!value;
}
@synthesize docUrl;
- (BOOL) hasDocType {
	return !!hasDocType_;
}
- (void) setHasDocType:(BOOL) value {
	hasDocType_ = !!value;
}
@synthesize docType;
- (BOOL) hasNumPages {
	return !!hasNumPages_;
}
- (void) setHasNumPages:(BOOL) value {
	hasNumPages_ = !!value;
}
@synthesize numPages;
- (BOOL) hasDocAmount {
	return !!hasDocAmount_;
}
- (void) setHasDocAmount:(BOOL) value {
	hasDocAmount_ = !!value;
}
@synthesize docAmount;
- (BOOL) hasDocCreditor {
	return !!hasDocCreditor_;
}
- (void) setHasDocCreditor:(BOOL) value {
	hasDocCreditor_ = !!value;
}
@synthesize docCreditor;
- (BOOL) hasDocDescription {
	return !!hasDocDescription_;
}
- (void) setHasDocDescription:(BOOL) value {
	hasDocDescription_ = !!value;
}
@synthesize docDescription;
@synthesize mutableArrPagesList;
- (void) dealloc {
	self.docId = nil;
	self.docName = nil;
	self.docUrl = nil;
	self.docType = nil;
	self.docAmount = nil;
	self.docCreditor = nil;
	self.docDescription = nil;
	self.mutableArrPagesList = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.docId = @"";
		self.docName = @"";
		self.docUrl = @"";
		self.docType = @"";
		self.numPages = 0;
		self.docAmount = @"";
		self.docCreditor = @"";
		self.docDescription = @"";
	}
	return self;
}
static MandantDefinition_Document* defaultMandantDefinition_DocumentInstance = nil;
+ (void) initialize {
	if (self == [MandantDefinition_Document class]) {
		defaultMandantDefinition_DocumentInstance = [[MandantDefinition_Document alloc] init];
	}
}
+ (MandantDefinition_Document*) defaultInstance {
	return defaultMandantDefinition_DocumentInstance;
}
- (MandantDefinition_Document*) defaultInstance {
	return defaultMandantDefinition_DocumentInstance;
}
- (NSArray*) arrPagesList {
	return mutableArrPagesList;
}
- (MandantDefinition_Page*) arrPagesAtIndex:(int32_t) index {
	id value = [mutableArrPagesList objectAtIndex:index];
	return value;
}
- (BOOL) isInitialized {
	return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
	if (self.hasDocId) {
		[output writeString:1 value:self.docId];
	}
	if (self.hasDocName) {
		[output writeString:2 value:self.docName];
	}
	if (self.hasDocUrl) {
		[output writeString:3 value:self.docUrl];
	}
	if (self.hasDocType) {
		[output writeString:4 value:self.docType];
	}
	if (self.hasNumPages) {
		[output writeInt32:5 value:self.numPages];
	}
	if (self.hasDocAmount) {
		[output writeString:6 value:self.docAmount];
	}
	if (self.hasDocCreditor) {
		[output writeString:7 value:self.docCreditor];
	}
	if (self.hasDocDescription) {
		[output writeString:8 value:self.docDescription];
	}
	for (MandantDefinition_Page* element in self.arrPagesList) {
		[output writeMessage:9 value:element];
	}
	[self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
	int32_t size = memoizedSerializedSize;
	if (size != -1) {
		return size;
	}
	
	size = 0;
	if (self.hasDocId) {
		size += computeStringSize(1, self.docId);
	}
	if (self.hasDocName) {
		size += computeStringSize(2, self.docName);
	}
	if (self.hasDocUrl) {
		size += computeStringSize(3, self.docUrl);
	}
	if (self.hasDocType) {
		size += computeStringSize(4, self.docType);
	}
	if (self.hasNumPages) {
		size += computeInt32Size(5, self.numPages);
	}
	if (self.hasDocAmount) {
		size += computeStringSize(6, self.docAmount);
	}
	if (self.hasDocCreditor) {
		size += computeStringSize(7, self.docCreditor);
	}
	if (self.hasDocDescription) {
		size += computeStringSize(8, self.docDescription);
	}
	for (MandantDefinition_Page* element in self.arrPagesList) {
		size += computeMessageSize(9, element);
	}
	size += self.unknownFields.serializedSize;
	memoizedSerializedSize = size;
	return size;
}
+ (MandantDefinition_Document*) parseFromData:(NSData*) data {
	return (MandantDefinition_Document*)[[[MandantDefinition_Document builder] mergeFromData:data] build];
}
+ (MandantDefinition_Document*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Document*)[[[MandantDefinition_Document builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Document*) parseFromInputStream:(NSInputStream*) input {
	return (MandantDefinition_Document*)[[[MandantDefinition_Document builder] mergeFromInputStream:input] build];
}
+ (MandantDefinition_Document*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Document*)[[[MandantDefinition_Document builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Document*) parseFromCodedInputStream:(PBCodedInputStream*) input {
	return (MandantDefinition_Document*)[[[MandantDefinition_Document builder] mergeFromCodedInputStream:input] build];
}
+ (MandantDefinition_Document*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Document*)[[[MandantDefinition_Document builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Document_Builder*) builder {
	return [[[MandantDefinition_Document_Builder alloc] init] autorelease];
}
+ (MandantDefinition_Document_Builder*) builderWithPrototype:(MandantDefinition_Document*) prototype {
	return [[MandantDefinition_Document builder] mergeFrom:prototype];
}
- (MandantDefinition_Document_Builder*) builder {
	return [MandantDefinition_Document builder];
}
@end

@interface MandantDefinition_Document_Builder()
@property (retain) MandantDefinition_Document* result;
@end

@implementation MandantDefinition_Document_Builder
@synthesize result;
- (void) dealloc {
	self.result = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.result = [[[MandantDefinition_Document alloc] init] autorelease];
	}
	return self;
}
- (PBGeneratedMessage*) internalGetResult {
	return result;
}
- (MandantDefinition_Document_Builder*) clear {
	self.result = [[[MandantDefinition_Document alloc] init] autorelease];
	return self;
}
- (MandantDefinition_Document_Builder*) clone {
	return [MandantDefinition_Document builderWithPrototype:result];
}
- (MandantDefinition_Document*) defaultInstance {
	return [MandantDefinition_Document defaultInstance];
}
- (MandantDefinition_Document*) build {
	[self checkInitialized];
	return [self buildPartial];
}
- (MandantDefinition_Document*) buildPartial {
	MandantDefinition_Document* returnMe = [[result retain] autorelease];
	self.result = nil;
	return returnMe;
}
- (MandantDefinition_Document_Builder*) mergeFrom:(MandantDefinition_Document*) other {
	if (other == [MandantDefinition_Document defaultInstance]) {
		return self;
	}
	if (other.hasDocId) {
		[self setDocId:other.docId];
	}
	if (other.hasDocName) {
		[self setDocName:other.docName];
	}
	if (other.hasDocUrl) {
		[self setDocUrl:other.docUrl];
	}
	if (other.hasDocType) {
		[self setDocType:other.docType];
	}
	if (other.hasNumPages) {
		[self setNumPages:other.numPages];
	}
	if (other.hasDocAmount) {
		[self setDocAmount:other.docAmount];
	}
	if (other.hasDocCreditor) {
		[self setDocCreditor:other.docCreditor];
	}
	if (other.hasDocDescription) {
		[self setDocDescription:other.docDescription];
	}
	if (other.mutableArrPagesList.count > 0) {
		if (result.mutableArrPagesList == nil) {
			result.mutableArrPagesList = [NSMutableArray array];
		}
		[result.mutableArrPagesList addObjectsFromArray:other.mutableArrPagesList];
	}
	[self mergeUnknownFields:other.unknownFields];
	return self;
}
- (MandantDefinition_Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
	return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MandantDefinition_Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
	while (YES) {
		int32_t tag = [input readTag];
		switch (tag) {
			case 0:
				[self setUnknownFields:[unknownFields build]];
				return self;
			default: {
				if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
					[self setUnknownFields:[unknownFields build]];
					return self;
				}
				break;
			}
			case 10: {
				[self setDocId:[input readString]];
				break;
			}
			case 18: {
				[self setDocName:[input readString]];
				break;
			}
			case 26: {
				[self setDocUrl:[input readString]];
				break;
			}
			case 34: {
				[self setDocType:[input readString]];
				break;
			}
			case 40: {
				[self setNumPages:[input readInt32]];
				break;
			}
			case 50: {
				[self setDocAmount:[input readString]];
				break;
			}
			case 58: {
				[self setDocCreditor:[input readString]];
				break;
			}
			case 66: {
				[self setDocDescription:[input readString]];
				break;
			}
			case 74: {
				MandantDefinition_Page_Builder* subBuilder = [MandantDefinition_Page builder];
				[input readMessage:subBuilder extensionRegistry:extensionRegistry];
				[self addArrPages:[subBuilder buildPartial]];
				break;
			}
		}
	}
}
- (BOOL) hasDocId {
	return result.hasDocId;
}
- (NSString*) docId {
	return result.docId;
}
- (MandantDefinition_Document_Builder*) setDocId:(NSString*) value {
	result.hasDocId = YES;
	result.docId = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocId {
	result.hasDocId = NO;
	result.docId = @"";
	return self;
}
- (BOOL) hasDocName {
	return result.hasDocName;
}
- (NSString*) docName {
	return result.docName;
}
- (MandantDefinition_Document_Builder*) setDocName:(NSString*) value {
	result.hasDocName = YES;
	result.docName = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocName {
	result.hasDocName = NO;
	result.docName = @"";
	return self;
}
- (BOOL) hasDocUrl {
	return result.hasDocUrl;
}
- (NSString*) docUrl {
	return result.docUrl;
}
- (MandantDefinition_Document_Builder*) setDocUrl:(NSString*) value {
	result.hasDocUrl = YES;
	result.docUrl = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocUrl {
	result.hasDocUrl = NO;
	result.docUrl = @"";
	return self;
}
- (BOOL) hasDocType {
	return result.hasDocType;
}
- (NSString*) docType {
	return result.docType;
}
- (MandantDefinition_Document_Builder*) setDocType:(NSString*) value {
	result.hasDocType = YES;
	result.docType = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocType {
	result.hasDocType = NO;
	result.docType = @"";
	return self;
}
- (BOOL) hasNumPages {
	return result.hasNumPages;
}
- (int32_t) numPages {
	return result.numPages;
}
- (MandantDefinition_Document_Builder*) setNumPages:(int32_t) value {
	result.hasNumPages = YES;
	result.numPages = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearNumPages {
	result.hasNumPages = NO;
	result.numPages = 0;
	return self;
}
- (BOOL) hasDocAmount {
	return result.hasDocAmount;
}
- (NSString*) docAmount {
	return result.docAmount;
}
- (MandantDefinition_Document_Builder*) setDocAmount:(NSString*) value {
	result.hasDocAmount = YES;
	result.docAmount = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocAmount {
	result.hasDocAmount = NO;
	result.docAmount = @"";
	return self;
}
- (BOOL) hasDocCreditor {
	return result.hasDocCreditor;
}
- (NSString*) docCreditor {
	return result.docCreditor;
}
- (MandantDefinition_Document_Builder*) setDocCreditor:(NSString*) value {
	result.hasDocCreditor = YES;
	result.docCreditor = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocCreditor {
	result.hasDocCreditor = NO;
	result.docCreditor = @"";
	return self;
}
- (BOOL) hasDocDescription {
	return result.hasDocDescription;
}
- (NSString*) docDescription {
	return result.docDescription;
}
- (MandantDefinition_Document_Builder*) setDocDescription:(NSString*) value {
	result.hasDocDescription = YES;
	result.docDescription = value;
	return self;
}
- (MandantDefinition_Document_Builder*) clearDocDescription {
	result.hasDocDescription = NO;
	result.docDescription = @"";
	return self;
}
- (NSArray*) arrPagesList {
	if (result.mutableArrPagesList == nil) { return [NSArray array]; }
	return result.mutableArrPagesList;
}
- (MandantDefinition_Page*) arrPagesAtIndex:(int32_t) index {
	return [result arrPagesAtIndex:index];
}
- (MandantDefinition_Document_Builder*) replaceArrPagesAtIndex:(int32_t) index with:(MandantDefinition_Page*) value {
	[result.mutableArrPagesList replaceObjectAtIndex:index withObject:value];
	return self;
}
- (MandantDefinition_Document_Builder*) addAllArrPages:(NSArray*) values {
	if (result.mutableArrPagesList == nil) {
		result.mutableArrPagesList = [NSMutableArray array];
	}
	[result.mutableArrPagesList addObjectsFromArray:values];
	return self;
}
- (MandantDefinition_Document_Builder*) clearArrPagesList {
	result.mutableArrPagesList = nil;
	return self;
}
- (MandantDefinition_Document_Builder*) addArrPages:(MandantDefinition_Page*) value {
	if (result.mutableArrPagesList == nil) {
		result.mutableArrPagesList = [NSMutableArray array];
	}
	[result.mutableArrPagesList addObject:value];
	return self;
}
@end

@interface MandantDefinition_Process ()
@property (retain) NSString* proId;
@property (retain) NSString* proName;
@property (retain) NSString* proUrl;
@property (retain) NSString* proDescription;
@property BOOL readStatus;
@property int32_t numDocs;
@property (retain) NSString* proEntryDate;
@property (retain) NSString* proType;
@property (retain) NSMutableArray* mutableArrDocsList;
@end

@implementation MandantDefinition_Process

- (BOOL) hasProId {
	return !!hasProId_;
}
- (void) setHasProId:(BOOL) value {
	hasProId_ = !!value;
}
@synthesize proId;
- (BOOL) hasProName {
	return !!hasProName_;
}
- (void) setHasProName:(BOOL) value {
	hasProName_ = !!value;
}
@synthesize proName;
- (BOOL) hasProUrl {
	return !!hasProUrl_;
}
- (void) setHasProUrl:(BOOL) value {
	hasProUrl_ = !!value;
}
@synthesize proUrl;
- (BOOL) hasProDescription {
	return !!hasProDescription_;
}
- (void) setHasProDescription:(BOOL) value {
	hasProDescription_ = !!value;
}
@synthesize proDescription;
- (BOOL) hasReadStatus {
	return !!hasReadStatus_;
}
- (void) setHasReadStatus:(BOOL) value {
	hasReadStatus_ = !!value;
}
- (BOOL) readStatus {
	return !!readStatus_;
}
- (void) setReadStatus:(BOOL) value {
	readStatus_ = !!value;
}
- (BOOL) hasNumDocs {
	return !!hasNumDocs_;
}
- (void) setHasNumDocs:(BOOL) value {
	hasNumDocs_ = !!value;
}
@synthesize numDocs;
- (BOOL) hasProEntryDate {
	return !!hasProEntryDate_;
}
- (void) setHasProEntryDate:(BOOL) value {
	hasProEntryDate_ = !!value;
}
@synthesize proEntryDate;
- (BOOL) hasProType {
	return !!hasProType_;
}
- (void) setHasProType:(BOOL) value {
	hasProType_ = !!value;
}
@synthesize proType;
@synthesize mutableArrDocsList;
- (void) dealloc {
	self.proId = nil;
	self.proName = nil;
	self.proUrl = nil;
	self.proDescription = nil;
	self.proEntryDate = nil;
	self.proType = nil;
	self.mutableArrDocsList = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.proId = @"";
		self.proName = @"";
		self.proUrl = @"";
		self.proDescription = @"";
		self.readStatus = NO;
		self.numDocs = 0;
		self.proEntryDate = @"";
		self.proType = @"";
	}
	return self;
}
static MandantDefinition_Process* defaultMandantDefinition_ProcessInstance = nil;
+ (void) initialize {
	if (self == [MandantDefinition_Process class]) {
		defaultMandantDefinition_ProcessInstance = [[MandantDefinition_Process alloc] init];
	}
}
+ (MandantDefinition_Process*) defaultInstance {
	return defaultMandantDefinition_ProcessInstance;
}
- (MandantDefinition_Process*) defaultInstance {
	return defaultMandantDefinition_ProcessInstance;
}
- (NSArray*) arrDocsList {
	return mutableArrDocsList;
}
- (MandantDefinition_Document*) arrDocsAtIndex:(int32_t) index {
	id value = [mutableArrDocsList objectAtIndex:index];
	return value;
}
- (BOOL) isInitialized {
	return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
	if (self.hasProId) {
		[output writeString:1 value:self.proId];
	}
	if (self.hasProName) {
		[output writeString:2 value:self.proName];
	}
	if (self.hasProUrl) {
		[output writeString:3 value:self.proUrl];
	}
	if (self.hasProDescription) {
		[output writeString:4 value:self.proDescription];
	}
	if (self.hasReadStatus) {
		[output writeBool:5 value:self.readStatus];
	}
	if (self.hasNumDocs) {
		[output writeInt32:6 value:self.numDocs];
	}
	if (self.hasProEntryDate) {
		[output writeString:7 value:self.proEntryDate];
	}
	if (self.hasProType) {
		[output writeString:8 value:self.proType];
	}
	for (MandantDefinition_Document* element in self.arrDocsList) {
		[output writeMessage:9 value:element];
	}
	[self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
	int32_t size = memoizedSerializedSize;
	if (size != -1) {
		return size;
	}
	
	size = 0;
	if (self.hasProId) {
		size += computeStringSize(1, self.proId);
	}
	if (self.hasProName) {
		size += computeStringSize(2, self.proName);
	}
	if (self.hasProUrl) {
		size += computeStringSize(3, self.proUrl);
	}
	if (self.hasProDescription) {
		size += computeStringSize(4, self.proDescription);
	}
	if (self.hasReadStatus) {
		size += computeBoolSize(5, self.readStatus);
	}
	if (self.hasNumDocs) {
		size += computeInt32Size(6, self.numDocs);
	}
	if (self.hasProEntryDate) {
		size += computeStringSize(7, self.proEntryDate);
	}
	if (self.hasProType) {
		size += computeStringSize(8, self.proType);
	}
	for (MandantDefinition_Document* element in self.arrDocsList) {
		size += computeMessageSize(9, element);
	}
	size += self.unknownFields.serializedSize;
	memoizedSerializedSize = size;
	return size;
}
+ (MandantDefinition_Process*) parseFromData:(NSData*) data {
	return (MandantDefinition_Process*)[[[MandantDefinition_Process builder] mergeFromData:data] build];
}
+ (MandantDefinition_Process*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Process*)[[[MandantDefinition_Process builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Process*) parseFromInputStream:(NSInputStream*) input {
	return (MandantDefinition_Process*)[[[MandantDefinition_Process builder] mergeFromInputStream:input] build];
}
+ (MandantDefinition_Process*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Process*)[[[MandantDefinition_Process builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Process*) parseFromCodedInputStream:(PBCodedInputStream*) input {
	return (MandantDefinition_Process*)[[[MandantDefinition_Process builder] mergeFromCodedInputStream:input] build];
}
+ (MandantDefinition_Process*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_Process*)[[[MandantDefinition_Process builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_Process_Builder*) builder {
	return [[[MandantDefinition_Process_Builder alloc] init] autorelease];
}
+ (MandantDefinition_Process_Builder*) builderWithPrototype:(MandantDefinition_Process*) prototype {
	return [[MandantDefinition_Process builder] mergeFrom:prototype];
}
- (MandantDefinition_Process_Builder*) builder {
	return [MandantDefinition_Process builder];
}
@end

@interface MandantDefinition_Process_Builder()
@property (retain) MandantDefinition_Process* result;
@end

@implementation MandantDefinition_Process_Builder
@synthesize result;
- (void) dealloc {
	self.result = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.result = [[[MandantDefinition_Process alloc] init] autorelease];
	}
	return self;
}
- (PBGeneratedMessage*) internalGetResult {
	return result;
}
- (MandantDefinition_Process_Builder*) clear {
	self.result = [[[MandantDefinition_Process alloc] init] autorelease];
	return self;
}
- (MandantDefinition_Process_Builder*) clone {
	return [MandantDefinition_Process builderWithPrototype:result];
}
- (MandantDefinition_Process*) defaultInstance {
	return [MandantDefinition_Process defaultInstance];
}
- (MandantDefinition_Process*) build {
	[self checkInitialized];
	return [self buildPartial];
}
- (MandantDefinition_Process*) buildPartial {
	MandantDefinition_Process* returnMe = [[result retain] autorelease];
	self.result = nil;
	return returnMe;
}
- (MandantDefinition_Process_Builder*) mergeFrom:(MandantDefinition_Process*) other {
	if (other == [MandantDefinition_Process defaultInstance]) {
		return self;
	}
	if (other.hasProId) {
		[self setProId:other.proId];
	}
	if (other.hasProName) {
		[self setProName:other.proName];
	}
	if (other.hasProUrl) {
		[self setProUrl:other.proUrl];
	}
	if (other.hasProDescription) {
		[self setProDescription:other.proDescription];
	}
	if (other.hasReadStatus) {
		[self setReadStatus:other.readStatus];
	}
	if (other.hasNumDocs) {
		[self setNumDocs:other.numDocs];
	}
	if (other.hasProEntryDate) {
		[self setProEntryDate:other.proEntryDate];
	}
	if (other.hasProType) {
		[self setProType:other.proType];
	}
	if (other.mutableArrDocsList.count > 0) {
		if (result.mutableArrDocsList == nil) {
			result.mutableArrDocsList = [NSMutableArray array];
		}
		[result.mutableArrDocsList addObjectsFromArray:other.mutableArrDocsList];
	}
	[self mergeUnknownFields:other.unknownFields];
	return self;
}
- (MandantDefinition_Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
	return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MandantDefinition_Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
	while (YES) {
		int32_t tag = [input readTag];
		switch (tag) {
			case 0:
				[self setUnknownFields:[unknownFields build]];
				return self;
			default: {
				if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
					[self setUnknownFields:[unknownFields build]];
					return self;
				}
				break;
			}
			case 10: {
				[self setProId:[input readString]];
				break;
			}
			case 18: {
				[self setProName:[input readString]];
				break;
			}
			case 26: {
				[self setProUrl:[input readString]];
				break;
			}
			case 34: {
				[self setProDescription:[input readString]];
				break;
			}
			case 40: {
				[self setReadStatus:[input readBool]];
				break;
			}
			case 48: {
				[self setNumDocs:[input readInt32]];
				break;
			}
			case 58: {
				[self setProEntryDate:[input readString]];
				break;
			}
			case 66: {
				[self setProType:[input readString]];
				break;
			}
			case 74: {
				MandantDefinition_Document_Builder* subBuilder = [MandantDefinition_Document builder];
				[input readMessage:subBuilder extensionRegistry:extensionRegistry];
				[self addArrDocs:[subBuilder buildPartial]];
				break;
			}
		}
	}
}
- (BOOL) hasProId {
	return result.hasProId;
}
- (NSString*) proId {
	return result.proId;
}
- (MandantDefinition_Process_Builder*) setProId:(NSString*) value {
	result.hasProId = YES;
	result.proId = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearProId {
	result.hasProId = NO;
	result.proId = @"";
	return self;
}
- (BOOL) hasProName {
	return result.hasProName;
}
- (NSString*) proName {
	return result.proName;
}
- (MandantDefinition_Process_Builder*) setProName:(NSString*) value {
	result.hasProName = YES;
	result.proName = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearProName {
	result.hasProName = NO;
	result.proName = @"";
	return self;
}
- (BOOL) hasProUrl {
	return result.hasProUrl;
}
- (NSString*) proUrl {
	return result.proUrl;
}
- (MandantDefinition_Process_Builder*) setProUrl:(NSString*) value {
	result.hasProUrl = YES;
	result.proUrl = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearProUrl {
	result.hasProUrl = NO;
	result.proUrl = @"";
	return self;
}
- (BOOL) hasProDescription {
	return result.hasProDescription;
}
- (NSString*) proDescription {
	return result.proDescription;
}
- (MandantDefinition_Process_Builder*) setProDescription:(NSString*) value {
	result.hasProDescription = YES;
	result.proDescription = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearProDescription {
	result.hasProDescription = NO;
	result.proDescription = @"";
	return self;
}
- (BOOL) hasReadStatus {
	return result.hasReadStatus;
}
- (BOOL) readStatus {
	return result.readStatus;
}
- (MandantDefinition_Process_Builder*) setReadStatus:(BOOL) value {
	result.hasReadStatus = YES;
	result.readStatus = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearReadStatus {
	result.hasReadStatus = NO;
	result.readStatus = NO;
	return self;
}
- (BOOL) hasNumDocs {
	return result.hasNumDocs;
}
- (int32_t) numDocs {
	return result.numDocs;
}
- (MandantDefinition_Process_Builder*) setNumDocs:(int32_t) value {
	result.hasNumDocs = YES;
	result.numDocs = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearNumDocs {
	result.hasNumDocs = NO;
	result.numDocs = 0;
	return self;
}
- (BOOL) hasProEntryDate {
	return result.hasProEntryDate;
}
- (NSString*) proEntryDate {
	return result.proEntryDate;
}
- (MandantDefinition_Process_Builder*) setProEntryDate:(NSString*) value {
	result.hasProEntryDate = YES;
	result.proEntryDate = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearProEntryDate {
	result.hasProEntryDate = NO;
	result.proEntryDate = @"";
	return self;
}
- (BOOL) hasProType {
	return result.hasProType;
}
- (NSString*) proType {
	return result.proType;
}
- (MandantDefinition_Process_Builder*) setProType:(NSString*) value {
	result.hasProType = YES;
	result.proType = value;
	return self;
}
- (MandantDefinition_Process_Builder*) clearProType {
	result.hasProType = NO;
	result.proType = @"";
	return self;
}
- (NSArray*) arrDocsList {
	if (result.mutableArrDocsList == nil) { return [NSArray array]; }
	return result.mutableArrDocsList;
}
- (MandantDefinition_Document*) arrDocsAtIndex:(int32_t) index {
	return [result arrDocsAtIndex:index];
}
- (MandantDefinition_Process_Builder*) replaceArrDocsAtIndex:(int32_t) index with:(MandantDefinition_Document*) value {
	[result.mutableArrDocsList replaceObjectAtIndex:index withObject:value];
	return self;
}
- (MandantDefinition_Process_Builder*) addAllArrDocs:(NSArray*) values {
	if (result.mutableArrDocsList == nil) {
		result.mutableArrDocsList = [NSMutableArray array];
	}
	[result.mutableArrDocsList addObjectsFromArray:values];
	return self;
}
- (MandantDefinition_Process_Builder*) clearArrDocsList {
	result.mutableArrDocsList = nil;
	return self;
}
- (MandantDefinition_Process_Builder*) addArrDocs:(MandantDefinition_Document*) value {
	if (result.mutableArrDocsList == nil) {
		result.mutableArrDocsList = [NSMutableArray array];
	}
	[result.mutableArrDocsList addObject:value];
	return self;
}
@end

@interface MandantDefinition_WorkBasket ()
@property (retain) NSString* wbId;
@property (retain) NSString* wbName;
@property (retain) NSString* wbUrl;
@property (retain) NSString* groupname;
@property (retain) NSString* wbDescription;
@property (retain) NSString* lastBuildDate;
@property (retain) NSMutableArray* mutableArrProsList;
@end

@implementation MandantDefinition_WorkBasket

- (BOOL) hasWbId {
	return !!hasWbId_;
}
- (void) setHasWbId:(BOOL) value {
	hasWbId_ = !!value;
}
@synthesize wbId;
- (BOOL) hasWbName {
	return !!hasWbName_;
}
- (void) setHasWbName:(BOOL) value {
	hasWbName_ = !!value;
}
@synthesize wbName;
- (BOOL) hasWbUrl {
	return !!hasWbUrl_;
}
- (void) setHasWbUrl:(BOOL) value {
	hasWbUrl_ = !!value;
}
@synthesize wbUrl;
- (BOOL) hasGroupname {
	return !!hasGroupname_;
}
- (void) setHasGroupname:(BOOL) value {
	hasGroupname_ = !!value;
}
@synthesize groupname;
- (BOOL) hasWbDescription {
	return !!hasWbDescription_;
}
- (void) setHasWbDescription:(BOOL) value {
	hasWbDescription_ = !!value;
}
@synthesize wbDescription;
- (BOOL) hasLastBuildDate {
	return !!hasLastBuildDate_;
}
- (void) setHasLastBuildDate:(BOOL) value {
	hasLastBuildDate_ = !!value;
}
@synthesize lastBuildDate;
@synthesize mutableArrProsList;
- (void) dealloc {
	self.wbId = nil;
	self.wbName = nil;
	self.wbUrl = nil;
	self.groupname = nil;
	self.wbDescription = nil;
	self.lastBuildDate = nil;
	self.mutableArrProsList = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.wbId = @"";
		self.wbName = @"";
		self.wbUrl = @"";
		self.groupname = @"";
		self.wbDescription = @"";
		self.lastBuildDate = @"";
	}
	return self;
}
static MandantDefinition_WorkBasket* defaultMandantDefinition_WorkBasketInstance = nil;
+ (void) initialize {
	if (self == [MandantDefinition_WorkBasket class]) {
		defaultMandantDefinition_WorkBasketInstance = [[MandantDefinition_WorkBasket alloc] init];
	}
}
+ (MandantDefinition_WorkBasket*) defaultInstance {
	return defaultMandantDefinition_WorkBasketInstance;
}
- (MandantDefinition_WorkBasket*) defaultInstance {
	return defaultMandantDefinition_WorkBasketInstance;
}
- (NSArray*) arrProsList {
	return mutableArrProsList;
}
- (MandantDefinition_Process*) arrProsAtIndex:(int32_t) index {
	id value = [mutableArrProsList objectAtIndex:index];
	return value;
}
- (BOOL) isInitialized {
	return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
	if (self.hasWbId) {
		[output writeString:1 value:self.wbId];
	}
	if (self.hasWbName) {
		[output writeString:2 value:self.wbName];
	}
	if (self.hasWbUrl) {
		[output writeString:3 value:self.wbUrl];
	}
	if (self.hasGroupname) {
		[output writeString:4 value:self.groupname];
	}
	if (self.hasWbDescription) {
		[output writeString:5 value:self.wbDescription];
	}
	if (self.hasLastBuildDate) {
		[output writeString:6 value:self.lastBuildDate];
	}
	for (MandantDefinition_Process* element in self.arrProsList) {
		[output writeMessage:7 value:element];
	}
	[self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
	int32_t size = memoizedSerializedSize;
	if (size != -1) {
		return size;
	}
	
	size = 0;
	if (self.hasWbId) {
		size += computeStringSize(1, self.wbId);
	}
	if (self.hasWbName) {
		size += computeStringSize(2, self.wbName);
	}
	if (self.hasWbUrl) {
		size += computeStringSize(3, self.wbUrl);
	}
	if (self.hasGroupname) {
		size += computeStringSize(4, self.groupname);
	}
	if (self.hasWbDescription) {
		size += computeStringSize(5, self.wbDescription);
	}
	if (self.hasLastBuildDate) {
		size += computeStringSize(6, self.lastBuildDate);
	}
	for (MandantDefinition_Process* element in self.arrProsList) {
		size += computeMessageSize(7, element);
	}
	size += self.unknownFields.serializedSize;
	memoizedSerializedSize = size;
	return size;
}
+ (MandantDefinition_WorkBasket*) parseFromData:(NSData*) data {
	return (MandantDefinition_WorkBasket*)[[[MandantDefinition_WorkBasket builder] mergeFromData:data] build];
}
+ (MandantDefinition_WorkBasket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_WorkBasket*)[[[MandantDefinition_WorkBasket builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_WorkBasket*) parseFromInputStream:(NSInputStream*) input {
	return (MandantDefinition_WorkBasket*)[[[MandantDefinition_WorkBasket builder] mergeFromInputStream:input] build];
}
+ (MandantDefinition_WorkBasket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_WorkBasket*)[[[MandantDefinition_WorkBasket builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_WorkBasket*) parseFromCodedInputStream:(PBCodedInputStream*) input {
	return (MandantDefinition_WorkBasket*)[[[MandantDefinition_WorkBasket builder] mergeFromCodedInputStream:input] build];
}
+ (MandantDefinition_WorkBasket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantDefinition_WorkBasket*)[[[MandantDefinition_WorkBasket builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantDefinition_WorkBasket_Builder*) builder {
	return [[[MandantDefinition_WorkBasket_Builder alloc] init] autorelease];
}
+ (MandantDefinition_WorkBasket_Builder*) builderWithPrototype:(MandantDefinition_WorkBasket*) prototype {
	return [[MandantDefinition_WorkBasket builder] mergeFrom:prototype];
}
- (MandantDefinition_WorkBasket_Builder*) builder {
	return [MandantDefinition_WorkBasket builder];
}
@end

@interface MandantDefinition_WorkBasket_Builder()
@property (retain) MandantDefinition_WorkBasket* result;
@end

@implementation MandantDefinition_WorkBasket_Builder
@synthesize result;
- (void) dealloc {
	self.result = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.result = [[[MandantDefinition_WorkBasket alloc] init] autorelease];
	}
	return self;
}
- (PBGeneratedMessage*) internalGetResult {
	return result;
}
- (MandantDefinition_WorkBasket_Builder*) clear {
	self.result = [[[MandantDefinition_WorkBasket alloc] init] autorelease];
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clone {
	return [MandantDefinition_WorkBasket builderWithPrototype:result];
}
- (MandantDefinition_WorkBasket*) defaultInstance {
	return [MandantDefinition_WorkBasket defaultInstance];
}
- (MandantDefinition_WorkBasket*) build {
	[self checkInitialized];
	return [self buildPartial];
}
- (MandantDefinition_WorkBasket*) buildPartial {
	MandantDefinition_WorkBasket* returnMe = [[result retain] autorelease];
	self.result = nil;
	return returnMe;
}
- (MandantDefinition_WorkBasket_Builder*) mergeFrom:(MandantDefinition_WorkBasket*) other {
	if (other == [MandantDefinition_WorkBasket defaultInstance]) {
		return self;
	}
	if (other.hasWbId) {
		[self setWbId:other.wbId];
	}
	if (other.hasWbName) {
		[self setWbName:other.wbName];
	}
	if (other.hasWbUrl) {
		[self setWbUrl:other.wbUrl];
	}
	if (other.hasGroupname) {
		[self setGroupname:other.groupname];
	}
	if (other.hasWbDescription) {
		[self setWbDescription:other.wbDescription];
	}
	if (other.hasLastBuildDate) {
		[self setLastBuildDate:other.lastBuildDate];
	}
	if (other.mutableArrProsList.count > 0) {
		if (result.mutableArrProsList == nil) {
			result.mutableArrProsList = [NSMutableArray array];
		}
		[result.mutableArrProsList addObjectsFromArray:other.mutableArrProsList];
	}
	[self mergeUnknownFields:other.unknownFields];
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
	return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MandantDefinition_WorkBasket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
	while (YES) {
		int32_t tag = [input readTag];
		switch (tag) {
			case 0:
				[self setUnknownFields:[unknownFields build]];
				return self;
			default: {
				if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
					[self setUnknownFields:[unknownFields build]];
					return self;
				}
				break;
			}
			case 10: {
				[self setWbId:[input readString]];
				break;
			}
			case 18: {
				[self setWbName:[input readString]];
				break;
			}
			case 26: {
				[self setWbUrl:[input readString]];
				break;
			}
			case 34: {
				[self setGroupname:[input readString]];
				break;
			}
			case 42: {
				[self setWbDescription:[input readString]];
				break;
			}
			case 50: {
				[self setLastBuildDate:[input readString]];
				break;
			}
			case 58: {
				MandantDefinition_Process_Builder* subBuilder = [MandantDefinition_Process builder];
				[input readMessage:subBuilder extensionRegistry:extensionRegistry];
				[self addArrPros:[subBuilder buildPartial]];
				break;
			}
		}
	}
}
- (BOOL) hasWbId {
	return result.hasWbId;
}
- (NSString*) wbId {
	return result.wbId;
}
- (MandantDefinition_WorkBasket_Builder*) setWbId:(NSString*) value {
	result.hasWbId = YES;
	result.wbId = value;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearWbId {
	result.hasWbId = NO;
	result.wbId = @"";
	return self;
}
- (BOOL) hasWbName {
	return result.hasWbName;
}
- (NSString*) wbName {
	return result.wbName;
}
- (MandantDefinition_WorkBasket_Builder*) setWbName:(NSString*) value {
	result.hasWbName = YES;
	result.wbName = value;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearWbName {
	result.hasWbName = NO;
	result.wbName = @"";
	return self;
}
- (BOOL) hasWbUrl {
	return result.hasWbUrl;
}
- (NSString*) wbUrl {
	return result.wbUrl;
}
- (MandantDefinition_WorkBasket_Builder*) setWbUrl:(NSString*) value {
	result.hasWbUrl = YES;
	result.wbUrl = value;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearWbUrl {
	result.hasWbUrl = NO;
	result.wbUrl = @"";
	return self;
}
- (BOOL) hasGroupname {
	return result.hasGroupname;
}
- (NSString*) groupname {
	return result.groupname;
}
- (MandantDefinition_WorkBasket_Builder*) setGroupname:(NSString*) value {
	result.hasGroupname = YES;
	result.groupname = value;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearGroupname {
	result.hasGroupname = NO;
	result.groupname = @"";
	return self;
}
- (BOOL) hasWbDescription {
	return result.hasWbDescription;
}
- (NSString*) wbDescription {
	return result.wbDescription;
}
- (MandantDefinition_WorkBasket_Builder*) setWbDescription:(NSString*) value {
	result.hasWbDescription = YES;
	result.wbDescription = value;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearWbDescription {
	result.hasWbDescription = NO;
	result.wbDescription = @"";
	return self;
}
- (BOOL) hasLastBuildDate {
	return result.hasLastBuildDate;
}
- (NSString*) lastBuildDate {
	return result.lastBuildDate;
}
- (MandantDefinition_WorkBasket_Builder*) setLastBuildDate:(NSString*) value {
	result.hasLastBuildDate = YES;
	result.lastBuildDate = value;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearLastBuildDate {
	result.hasLastBuildDate = NO;
	result.lastBuildDate = @"";
	return self;
}
- (NSArray*) arrProsList {
	if (result.mutableArrProsList == nil) { return [NSArray array]; }
	return result.mutableArrProsList;
}
- (MandantDefinition_Process*) arrProsAtIndex:(int32_t) index {
	return [result arrProsAtIndex:index];
}
- (MandantDefinition_WorkBasket_Builder*) replaceArrProsAtIndex:(int32_t) index with:(MandantDefinition_Process*) value {
	[result.mutableArrProsList replaceObjectAtIndex:index withObject:value];
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) addAllArrPros:(NSArray*) values {
	if (result.mutableArrProsList == nil) {
		result.mutableArrProsList = [NSMutableArray array];
	}
	[result.mutableArrProsList addObjectsFromArray:values];
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) clearArrProsList {
	result.mutableArrProsList = nil;
	return self;
}
- (MandantDefinition_WorkBasket_Builder*) addArrPros:(MandantDefinition_Process*) value {
	if (result.mutableArrProsList == nil) {
		result.mutableArrProsList = [NSMutableArray array];
	}
	[result.mutableArrProsList addObject:value];
	return self;
}
@end

@interface MandantDefinition_Builder()
@property (retain) MandantDefinition* result;
@end

@implementation MandantDefinition_Builder
@synthesize result;
- (void) dealloc {
	self.result = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.result = [[[MandantDefinition alloc] init] autorelease];
	}
	return self;
}
- (PBGeneratedMessage*) internalGetResult {
	return result;
}
- (MandantDefinition_Builder*) clear {
	self.result = [[[MandantDefinition alloc] init] autorelease];
	return self;
}
- (MandantDefinition_Builder*) clone {
	return [MandantDefinition builderWithPrototype:result];
}
- (MandantDefinition*) defaultInstance {
	return [MandantDefinition defaultInstance];
}
- (MandantDefinition*) build {
	[self checkInitialized];
	return [self buildPartial];
}
- (MandantDefinition*) buildPartial {
	MandantDefinition* returnMe = [[result retain] autorelease];
	self.result = nil;
	return returnMe;
}
- (MandantDefinition_Builder*) mergeFrom:(MandantDefinition*) other {
	if (other == [MandantDefinition defaultInstance]) {
		return self;
	}
	if (other.hasId) {
		[self setId:other.id];
	}
	if (other.hasName) {
		[self setName:other.name];
	}
	if (other.hasUrl) {
		[self setUrl:other.url];
	}
	if (other.hasDescription) {
		[self setDescription:other.description];
	}
	if (other.hasAdded) {
		[self setAdded:other.added];
	}
	if (other.mutableArrWbsList.count > 0) {
		if (result.mutableArrWbsList == nil) {
			result.mutableArrWbsList = [NSMutableArray array];
		}
		[result.mutableArrWbsList addObjectsFromArray:other.mutableArrWbsList];
	}
	[self mergeUnknownFields:other.unknownFields];
	return self;
}
- (MandantDefinition_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
	return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MandantDefinition_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
	while (YES) {
		int32_t tag = [input readTag];
		switch (tag) {
			case 0:
				[self setUnknownFields:[unknownFields build]];
				return self;
			default: {
				if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
					[self setUnknownFields:[unknownFields build]];
					return self;
				}
				break;
			}
			case 10: {
				[self setId:[input readString]];
				break;
			}
			case 18: {
				[self setName:[input readString]];
				break;
			}
			case 26: {
				[self setUrl:[input readString]];
				break;
			}
			case 34: {
				[self setDescription:[input readString]];
				break;
			}
			case 40: {
				[self setAdded:[input readBool]];
				break;
			}
			case 50: {
				MandantDefinition_WorkBasket_Builder* subBuilder = [MandantDefinition_WorkBasket builder];
				[input readMessage:subBuilder extensionRegistry:extensionRegistry];
				[self addArrWbs:[subBuilder buildPartial]];
				break;
			}
		}
	}
}
- (BOOL) hasId {
	return result.hasId;
}
- (NSString*) id {
	return result.id;
}
- (MandantDefinition_Builder*) setId:(NSString*) value {
	result.hasId = YES;
	result.id = value;
	return self;
}
- (MandantDefinition_Builder*) clearId {
	result.hasId = NO;
	result.id = @"";
	return self;
}
- (BOOL) hasName {
	return result.hasName;
}
- (NSString*) name {
	return result.name;
}
- (MandantDefinition_Builder*) setName:(NSString*) value {
	result.hasName = YES;
	result.name = value;
	return self;
}
- (MandantDefinition_Builder*) clearName {
	result.hasName = NO;
	result.name = @"";
	return self;
}
- (BOOL) hasUrl {
	return result.hasUrl;
}
- (NSString*) url {
	return result.url;
}
- (MandantDefinition_Builder*) setUrl:(NSString*) value {
	result.hasUrl = YES;
	result.url = value;
	return self;
}
- (MandantDefinition_Builder*) clearUrl {
	result.hasUrl = NO;
	result.url = @"";
	return self;
}
- (BOOL) hasDescription {
	return result.hasDescription;
}
- (NSString*) description {
	return result.description;
}
- (MandantDefinition_Builder*) setDescription:(NSString*) value {
	result.hasDescription = YES;
	result.description = value;
	return self;
}
- (MandantDefinition_Builder*) clearDescription {
	result.hasDescription = NO;
	result.description = @"";
	return self;
}
- (BOOL) hasAdded {
	return result.hasAdded;
}
- (BOOL) added {
	return result.added;
}
- (MandantDefinition_Builder*) setAdded:(BOOL) value {
	result.hasAdded = YES;
	result.added = value;
	return self;
}
- (MandantDefinition_Builder*) clearAdded {
	result.hasAdded = NO;
	result.added = NO;
	return self;
}
- (NSArray*) arrWbsList {
	if (result.mutableArrWbsList == nil) { return [NSArray array]; }
	return result.mutableArrWbsList;
}
- (MandantDefinition_WorkBasket*) arrWbsAtIndex:(int32_t) index {
	return [result arrWbsAtIndex:index];
}
- (MandantDefinition_Builder*) replaceArrWbsAtIndex:(int32_t) index with:(MandantDefinition_WorkBasket*) value {
	[result.mutableArrWbsList replaceObjectAtIndex:index withObject:value];
	return self;
}
- (MandantDefinition_Builder*) addAllArrWbs:(NSArray*) values {
	if (result.mutableArrWbsList == nil) {
		result.mutableArrWbsList = [NSMutableArray array];
	}
	[result.mutableArrWbsList addObjectsFromArray:values];
	return self;
}
- (MandantDefinition_Builder*) clearArrWbsList {
	result.mutableArrWbsList = nil;
	return self;
}
- (MandantDefinition_Builder*) addArrWbs:(MandantDefinition_WorkBasket*) value {
	if (result.mutableArrWbsList == nil) {
		result.mutableArrWbsList = [NSMutableArray array];
	}
	[result.mutableArrWbsList addObject:value];
	return self;
}
@end

@interface MandantCOLLECTION ()
@property (retain) NSMutableArray* mutableMandantList;
@end

@implementation MandantCOLLECTION

@synthesize mutableMandantList;
- (void) dealloc {
	self.mutableMandantList = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
	}
	return self;
}
static MandantCOLLECTION* defaultMandantCOLLECTIONInstance = nil;
+ (void) initialize {
	if (self == [MandantCOLLECTION class]) {
		defaultMandantCOLLECTIONInstance = [[MandantCOLLECTION alloc] init];
	}
}
+ (MandantCOLLECTION*) defaultInstance {
	return defaultMandantCOLLECTIONInstance;
}
- (MandantCOLLECTION*) defaultInstance {
	return defaultMandantCOLLECTIONInstance;
}
- (NSArray*) mandantList {
	return mutableMandantList;
}
- (MandantDefinition*) mandantAtIndex:(int32_t) index {
	id value = [mutableMandantList objectAtIndex:index];
	return value;
}
- (BOOL) isInitialized {
	return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
	for (MandantDefinition* element in self.mandantList) {
		[output writeMessage:1 value:element];
	}
	[self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
	int32_t size = memoizedSerializedSize;
	if (size != -1) {
		return size;
	}
	
	size = 0;
	for (MandantDefinition* element in self.mandantList) {
		size += computeMessageSize(1, element);
	}
	size += self.unknownFields.serializedSize;
	memoizedSerializedSize = size;
	return size;
}
+ (MandantCOLLECTION*) parseFromData:(NSData*) data {
	return (MandantCOLLECTION*)[[[MandantCOLLECTION builder] mergeFromData:data] build];
}
+ (MandantCOLLECTION*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantCOLLECTION*)[[[MandantCOLLECTION builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MandantCOLLECTION*) parseFromInputStream:(NSInputStream*) input {
	return (MandantCOLLECTION*)[[[MandantCOLLECTION builder] mergeFromInputStream:input] build];
}
+ (MandantCOLLECTION*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantCOLLECTION*)[[[MandantCOLLECTION builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantCOLLECTION*) parseFromCodedInputStream:(PBCodedInputStream*) input {
	return (MandantCOLLECTION*)[[[MandantCOLLECTION builder] mergeFromCodedInputStream:input] build];
}
+ (MandantCOLLECTION*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	return (MandantCOLLECTION*)[[[MandantCOLLECTION builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MandantCOLLECTION_Builder*) builder {
	return [[[MandantCOLLECTION_Builder alloc] init] autorelease];
}
+ (MandantCOLLECTION_Builder*) builderWithPrototype:(MandantCOLLECTION*) prototype {
	return [[MandantCOLLECTION builder] mergeFrom:prototype];
}
- (MandantCOLLECTION_Builder*) builder {
	return [MandantCOLLECTION builder];
}
@end

@interface MandantCOLLECTION_Builder()
@property (retain) MandantCOLLECTION* result;
@end

@implementation MandantCOLLECTION_Builder
@synthesize result;
- (void) dealloc {
	self.result = nil;
	[super dealloc];
}
- (id) init {
	if ((self = [super init])) {
		self.result = [[[MandantCOLLECTION alloc] init] autorelease];
	}
	return self;
}
- (PBGeneratedMessage*) internalGetResult {
	return result;
}
- (MandantCOLLECTION_Builder*) clear {
	self.result = [[[MandantCOLLECTION alloc] init] autorelease];
	return self;
}
- (MandantCOLLECTION_Builder*) clone {
	return [MandantCOLLECTION builderWithPrototype:result];
}
- (MandantCOLLECTION*) defaultInstance {
	return [MandantCOLLECTION defaultInstance];
}
- (MandantCOLLECTION*) build {
	[self checkInitialized];
	return [self buildPartial];
}
- (MandantCOLLECTION*) buildPartial {
	MandantCOLLECTION* returnMe = [[result retain] autorelease];
	self.result = nil;
	return returnMe;
}
- (MandantCOLLECTION_Builder*) mergeFrom:(MandantCOLLECTION*) other {
	if (other == [MandantCOLLECTION defaultInstance]) {
		return self;
	}
	if (other.mutableMandantList.count > 0) {
		if (result.mutableMandantList == nil) {
			result.mutableMandantList = [NSMutableArray array];
		}
		[result.mutableMandantList addObjectsFromArray:other.mutableMandantList];
	}
	[self mergeUnknownFields:other.unknownFields];
	return self;
}
- (MandantCOLLECTION_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
	return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MandantCOLLECTION_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
	PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
	while (YES) {
		int32_t tag = [input readTag];
		switch (tag) {
			case 0:
				[self setUnknownFields:[unknownFields build]];
				return self;
			default: {
				if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
					[self setUnknownFields:[unknownFields build]];
					return self;
				}
				break;
			}
			case 10: {
				MandantDefinition_Builder* subBuilder = [MandantDefinition builder];
				[input readMessage:subBuilder extensionRegistry:extensionRegistry];
				[self addMandant:[subBuilder buildPartial]];
				break;
			}
		}
	}
}
- (NSArray*) mandantList {
	if (result.mutableMandantList == nil) { return [NSArray array]; }
	return result.mutableMandantList;
}
- (MandantDefinition*) mandantAtIndex:(int32_t) index {
	return [result mandantAtIndex:index];
}
- (MandantCOLLECTION_Builder*) replaceMandantAtIndex:(int32_t) index with:(MandantDefinition*) value {
	[result.mutableMandantList replaceObjectAtIndex:index withObject:value];
	return self;
}
- (MandantCOLLECTION_Builder*) addAllMandant:(NSArray*) values {
	if (result.mutableMandantList == nil) {
		result.mutableMandantList = [NSMutableArray array];
	}
	[result.mutableMandantList addObjectsFromArray:values];
	return self;
}
- (MandantCOLLECTION_Builder*) clearMandantList {
	result.mutableMandantList = nil;
	return self;
}
- (MandantCOLLECTION_Builder*) addMandant:(MandantDefinition*) value {
	if (result.mutableMandantList == nil) {
		result.mutableMandantList = [NSMutableArray array];
	}
	[result.mutableMandantList addObject:value];
	return self;
}
@end

