// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Document;
@class DocumentList;
@class DocumentList_Builder;
@class Document_Builder;
@class Process;
@class ProcessList;
@class ProcessList_Builder;
@class Process_Builder;

@interface ProcessListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Process : PBGeneratedMessage {
@private
  BOOL hasPId_:1;
  BOOL hasOrderId_:1;
  BOOL hasTypeId_:1;
  BOOL hasEntryDate_:1;
  BOOL hasDocumentList_:1;
  NSString* pId;
  NSString* orderId;
  NSString* typeId;
  NSString* entryDate;
  DocumentList* documentList;
}
- (BOOL) hasPId;
- (BOOL) hasOrderId;
- (BOOL) hasTypeId;
- (BOOL) hasEntryDate;
- (BOOL) hasDocumentList;
@property (readonly, retain) NSString* pId;
@property (readonly, retain) NSString* orderId;
@property (readonly, retain) NSString* typeId;
@property (readonly, retain) NSString* entryDate;
@property (readonly, retain) DocumentList* documentList;

+ (Process*) defaultInstance;
- (Process*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Process_Builder*) builder;
+ (Process_Builder*) builder;
+ (Process_Builder*) builderWithPrototype:(Process*) prototype;

+ (Process*) parseFromData:(NSData*) data;
+ (Process*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Process*) parseFromInputStream:(NSInputStream*) input;
+ (Process*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Process*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Process*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Process_Builder : PBGeneratedMessage_Builder {
@private
  Process* result;
}

- (Process*) defaultInstance;

- (Process_Builder*) clear;
- (Process_Builder*) clone;

- (Process*) build;
- (Process*) buildPartial;

- (Process_Builder*) mergeFrom:(Process*) other;
- (Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPId;
- (NSString*) pId;
- (Process_Builder*) setPId:(NSString*) value;
- (Process_Builder*) clearPId;

- (BOOL) hasOrderId;
- (NSString*) orderId;
- (Process_Builder*) setOrderId:(NSString*) value;
- (Process_Builder*) clearOrderId;

- (BOOL) hasTypeId;
- (NSString*) typeId;
- (Process_Builder*) setTypeId:(NSString*) value;
- (Process_Builder*) clearTypeId;

- (BOOL) hasEntryDate;
- (NSString*) entryDate;
- (Process_Builder*) setEntryDate:(NSString*) value;
- (Process_Builder*) clearEntryDate;

- (BOOL) hasDocumentList;
- (DocumentList*) documentList;
- (Process_Builder*) setDocumentList:(DocumentList*) value;
- (Process_Builder*) setDocumentListBuilder:(DocumentList_Builder*) builderForValue;
- (Process_Builder*) mergeDocumentList:(DocumentList*) value;
- (Process_Builder*) clearDocumentList;
@end

@interface ProcessList : PBGeneratedMessage {
@private
  NSMutableArray* mutableProcessList;
}
- (NSArray*) processList;
- (Process*) processAtIndex:(int32_t) index;

+ (ProcessList*) defaultInstance;
- (ProcessList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProcessList_Builder*) builder;
+ (ProcessList_Builder*) builder;
+ (ProcessList_Builder*) builderWithPrototype:(ProcessList*) prototype;

+ (ProcessList*) parseFromData:(NSData*) data;
+ (ProcessList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessList*) parseFromInputStream:(NSInputStream*) input;
+ (ProcessList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProcessList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProcessList_Builder : PBGeneratedMessage_Builder {
@private
  ProcessList* result;
}

- (ProcessList*) defaultInstance;

- (ProcessList_Builder*) clear;
- (ProcessList_Builder*) clone;

- (ProcessList*) build;
- (ProcessList*) buildPartial;

- (ProcessList_Builder*) mergeFrom:(ProcessList*) other;
- (ProcessList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProcessList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) processList;
- (Process*) processAtIndex:(int32_t) index;
- (ProcessList_Builder*) replaceProcessAtIndex:(int32_t) index with:(Process*) value;
- (ProcessList_Builder*) addProcess:(Process*) value;
- (ProcessList_Builder*) addAllProcess:(NSArray*) values;
- (ProcessList_Builder*) clearProcessList;
@end

@interface Document : PBGeneratedMessage {
@private
  BOOL hasPageCount_:1;
  BOOL hasDId_:1;
  BOOL hasTypeId_:1;
  int32_t pageCount;
  NSString* dId;
  NSString* typeId;
}
- (BOOL) hasDId;
- (BOOL) hasTypeId;
- (BOOL) hasPageCount;
@property (readonly, retain) NSString* dId;
@property (readonly, retain) NSString* typeId;
@property (readonly) int32_t pageCount;

+ (Document*) defaultInstance;
- (Document*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Document_Builder*) builder;
+ (Document_Builder*) builder;
+ (Document_Builder*) builderWithPrototype:(Document*) prototype;

+ (Document*) parseFromData:(NSData*) data;
+ (Document*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Document*) parseFromInputStream:(NSInputStream*) input;
+ (Document*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Document*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Document*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Document_Builder : PBGeneratedMessage_Builder {
@private
  Document* result;
}

- (Document*) defaultInstance;

- (Document_Builder*) clear;
- (Document_Builder*) clone;

- (Document*) build;
- (Document*) buildPartial;

- (Document_Builder*) mergeFrom:(Document*) other;
- (Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDId;
- (NSString*) dId;
- (Document_Builder*) setDId:(NSString*) value;
- (Document_Builder*) clearDId;

- (BOOL) hasTypeId;
- (NSString*) typeId;
- (Document_Builder*) setTypeId:(NSString*) value;
- (Document_Builder*) clearTypeId;

- (BOOL) hasPageCount;
- (int32_t) pageCount;
- (Document_Builder*) setPageCount:(int32_t) value;
- (Document_Builder*) clearPageCount;
@end

@interface DocumentList : PBGeneratedMessage {
@private
  NSMutableArray* mutableDocumentList;
}
- (NSArray*) documentList;
- (Document*) documentAtIndex:(int32_t) index;

+ (DocumentList*) defaultInstance;
- (DocumentList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DocumentList_Builder*) builder;
+ (DocumentList_Builder*) builder;
+ (DocumentList_Builder*) builderWithPrototype:(DocumentList*) prototype;

+ (DocumentList*) parseFromData:(NSData*) data;
+ (DocumentList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DocumentList*) parseFromInputStream:(NSInputStream*) input;
+ (DocumentList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DocumentList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DocumentList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DocumentList_Builder : PBGeneratedMessage_Builder {
@private
  DocumentList* result;
}

- (DocumentList*) defaultInstance;

- (DocumentList_Builder*) clear;
- (DocumentList_Builder*) clone;

- (DocumentList*) build;
- (DocumentList*) buildPartial;

- (DocumentList_Builder*) mergeFrom:(DocumentList*) other;
- (DocumentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DocumentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) documentList;
- (Document*) documentAtIndex:(int32_t) index;
- (DocumentList_Builder*) replaceDocumentAtIndex:(int32_t) index with:(Document*) value;
- (DocumentList_Builder*) addDocument:(Document*) value;
- (DocumentList_Builder*) addAllDocument:(NSArray*) values;
- (DocumentList_Builder*) clearDocumentList;
@end

