// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BasketProcessId;
@class BasketProcessIdList;
@class BasketProcessIdList_Builder;
@class BasketProcessId_Builder;
@class BasketProcessIds;
@class BasketProcessIdsList;
@class BasketProcessIdsList_Builder;
@class BasketProcessIds_Builder;
@class ProcessIdList;
@class ProcessIdList_Builder;
@class ProcessIds;
@class ProcessIds_Builder;

@interface ProcessIdListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ProcessIds : PBGeneratedMessage {
@private
  BOOL hasPid_:1;
  BOOL hasOrderId_:1;
  NSString* pid;
  NSString* orderId;
}
- (BOOL) hasPid;
- (BOOL) hasOrderId;
@property (readonly, retain) NSString* pid;
@property (readonly, retain) NSString* orderId;

+ (ProcessIds*) defaultInstance;
- (ProcessIds*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProcessIds_Builder*) builder;
+ (ProcessIds_Builder*) builder;
+ (ProcessIds_Builder*) builderWithPrototype:(ProcessIds*) prototype;

+ (ProcessIds*) parseFromData:(NSData*) data;
+ (ProcessIds*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessIds*) parseFromInputStream:(NSInputStream*) input;
+ (ProcessIds*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessIds*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProcessIds*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProcessIds_Builder : PBGeneratedMessage_Builder {
@private
  ProcessIds* result;
}

- (ProcessIds*) defaultInstance;

- (ProcessIds_Builder*) clear;
- (ProcessIds_Builder*) clone;

- (ProcessIds*) build;
- (ProcessIds*) buildPartial;

- (ProcessIds_Builder*) mergeFrom:(ProcessIds*) other;
- (ProcessIds_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProcessIds_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPid;
- (NSString*) pid;
- (ProcessIds_Builder*) setPid:(NSString*) value;
- (ProcessIds_Builder*) clearPid;

- (BOOL) hasOrderId;
- (NSString*) orderId;
- (ProcessIds_Builder*) setOrderId:(NSString*) value;
- (ProcessIds_Builder*) clearOrderId;
@end

@interface BasketProcessIds : PBGeneratedMessage {
@private
  BOOL hasBasketId_:1;
  NSString* basketId;
  NSMutableArray* mutableProcessIdsList;
}
- (BOOL) hasBasketId;
@property (readonly, retain) NSString* basketId;
- (NSArray*) processIdsList;
- (ProcessIds*) processIdsAtIndex:(int32_t) index;

+ (BasketProcessIds*) defaultInstance;
- (BasketProcessIds*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BasketProcessIds_Builder*) builder;
+ (BasketProcessIds_Builder*) builder;
+ (BasketProcessIds_Builder*) builderWithPrototype:(BasketProcessIds*) prototype;

+ (BasketProcessIds*) parseFromData:(NSData*) data;
+ (BasketProcessIds*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessIds*) parseFromInputStream:(NSInputStream*) input;
+ (BasketProcessIds*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessIds*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BasketProcessIds*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BasketProcessIds_Builder : PBGeneratedMessage_Builder {
@private
  BasketProcessIds* result;
}

- (BasketProcessIds*) defaultInstance;

- (BasketProcessIds_Builder*) clear;
- (BasketProcessIds_Builder*) clone;

- (BasketProcessIds*) build;
- (BasketProcessIds*) buildPartial;

- (BasketProcessIds_Builder*) mergeFrom:(BasketProcessIds*) other;
- (BasketProcessIds_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BasketProcessIds_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBasketId;
- (NSString*) basketId;
- (BasketProcessIds_Builder*) setBasketId:(NSString*) value;
- (BasketProcessIds_Builder*) clearBasketId;

- (NSArray*) processIdsList;
- (ProcessIds*) processIdsAtIndex:(int32_t) index;
- (BasketProcessIds_Builder*) replaceProcessIdsAtIndex:(int32_t) index with:(ProcessIds*) value;
- (BasketProcessIds_Builder*) addProcessIds:(ProcessIds*) value;
- (BasketProcessIds_Builder*) addAllProcessIds:(NSArray*) values;
- (BasketProcessIds_Builder*) clearProcessIdsList;
@end

@interface BasketProcessIdsList : PBGeneratedMessage {
@private
  NSMutableArray* mutableBasketProcessIdsList;
}
- (NSArray*) basketProcessIdsList;
- (BasketProcessIds*) basketProcessIdsAtIndex:(int32_t) index;

+ (BasketProcessIdsList*) defaultInstance;
- (BasketProcessIdsList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BasketProcessIdsList_Builder*) builder;
+ (BasketProcessIdsList_Builder*) builder;
+ (BasketProcessIdsList_Builder*) builderWithPrototype:(BasketProcessIdsList*) prototype;

+ (BasketProcessIdsList*) parseFromData:(NSData*) data;
+ (BasketProcessIdsList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessIdsList*) parseFromInputStream:(NSInputStream*) input;
+ (BasketProcessIdsList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessIdsList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BasketProcessIdsList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BasketProcessIdsList_Builder : PBGeneratedMessage_Builder {
@private
  BasketProcessIdsList* result;
}

- (BasketProcessIdsList*) defaultInstance;

- (BasketProcessIdsList_Builder*) clear;
- (BasketProcessIdsList_Builder*) clone;

- (BasketProcessIdsList*) build;
- (BasketProcessIdsList*) buildPartial;

- (BasketProcessIdsList_Builder*) mergeFrom:(BasketProcessIdsList*) other;
- (BasketProcessIdsList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BasketProcessIdsList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) basketProcessIdsList;
- (BasketProcessIds*) basketProcessIdsAtIndex:(int32_t) index;
- (BasketProcessIdsList_Builder*) replaceBasketProcessIdsAtIndex:(int32_t) index with:(BasketProcessIds*) value;
- (BasketProcessIdsList_Builder*) addBasketProcessIds:(BasketProcessIds*) value;
- (BasketProcessIdsList_Builder*) addAllBasketProcessIds:(NSArray*) values;
- (BasketProcessIdsList_Builder*) clearBasketProcessIdsList;
@end

@interface BasketProcessId : PBGeneratedMessage {
@private
  BOOL hasBasketId_:1;
  NSString* basketId;
  NSMutableArray* mutablePidList;
}
- (BOOL) hasBasketId;
@property (readonly, retain) NSString* basketId;
- (NSArray*) pidList;
- (NSString*) pidAtIndex:(int32_t) index;

+ (BasketProcessId*) defaultInstance;
- (BasketProcessId*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BasketProcessId_Builder*) builder;
+ (BasketProcessId_Builder*) builder;
+ (BasketProcessId_Builder*) builderWithPrototype:(BasketProcessId*) prototype;

+ (BasketProcessId*) parseFromData:(NSData*) data;
+ (BasketProcessId*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessId*) parseFromInputStream:(NSInputStream*) input;
+ (BasketProcessId*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessId*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BasketProcessId*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BasketProcessId_Builder : PBGeneratedMessage_Builder {
@private
  BasketProcessId* result;
}

- (BasketProcessId*) defaultInstance;

- (BasketProcessId_Builder*) clear;
- (BasketProcessId_Builder*) clone;

- (BasketProcessId*) build;
- (BasketProcessId*) buildPartial;

- (BasketProcessId_Builder*) mergeFrom:(BasketProcessId*) other;
- (BasketProcessId_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BasketProcessId_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBasketId;
- (NSString*) basketId;
- (BasketProcessId_Builder*) setBasketId:(NSString*) value;
- (BasketProcessId_Builder*) clearBasketId;

- (NSArray*) pidList;
- (NSString*) pidAtIndex:(int32_t) index;
- (BasketProcessId_Builder*) replacePidAtIndex:(int32_t) index with:(NSString*) value;
- (BasketProcessId_Builder*) addPid:(NSString*) value;
- (BasketProcessId_Builder*) addAllPid:(NSArray*) values;
- (BasketProcessId_Builder*) clearPidList;
@end

@interface BasketProcessIdList : PBGeneratedMessage {
@private
  NSMutableArray* mutableBasketProcessIdList;
}
- (NSArray*) basketProcessIdList;
- (BasketProcessId*) basketProcessIdAtIndex:(int32_t) index;

+ (BasketProcessIdList*) defaultInstance;
- (BasketProcessIdList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BasketProcessIdList_Builder*) builder;
+ (BasketProcessIdList_Builder*) builder;
+ (BasketProcessIdList_Builder*) builderWithPrototype:(BasketProcessIdList*) prototype;

+ (BasketProcessIdList*) parseFromData:(NSData*) data;
+ (BasketProcessIdList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessIdList*) parseFromInputStream:(NSInputStream*) input;
+ (BasketProcessIdList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasketProcessIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BasketProcessIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BasketProcessIdList_Builder : PBGeneratedMessage_Builder {
@private
  BasketProcessIdList* result;
}

- (BasketProcessIdList*) defaultInstance;

- (BasketProcessIdList_Builder*) clear;
- (BasketProcessIdList_Builder*) clone;

- (BasketProcessIdList*) build;
- (BasketProcessIdList*) buildPartial;

- (BasketProcessIdList_Builder*) mergeFrom:(BasketProcessIdList*) other;
- (BasketProcessIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BasketProcessIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) basketProcessIdList;
- (BasketProcessId*) basketProcessIdAtIndex:(int32_t) index;
- (BasketProcessIdList_Builder*) replaceBasketProcessIdAtIndex:(int32_t) index with:(BasketProcessId*) value;
- (BasketProcessIdList_Builder*) addBasketProcessId:(BasketProcessId*) value;
- (BasketProcessIdList_Builder*) addAllBasketProcessId:(NSArray*) values;
- (BasketProcessIdList_Builder*) clearBasketProcessIdList;
@end

@interface ProcessIdList : PBGeneratedMessage {
@private
  NSMutableArray* mutablePidList;
}
- (NSArray*) pidList;
- (NSString*) pidAtIndex:(int32_t) index;

+ (ProcessIdList*) defaultInstance;
- (ProcessIdList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProcessIdList_Builder*) builder;
+ (ProcessIdList_Builder*) builder;
+ (ProcessIdList_Builder*) builderWithPrototype:(ProcessIdList*) prototype;

+ (ProcessIdList*) parseFromData:(NSData*) data;
+ (ProcessIdList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessIdList*) parseFromInputStream:(NSInputStream*) input;
+ (ProcessIdList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProcessIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProcessIdList_Builder : PBGeneratedMessage_Builder {
@private
  ProcessIdList* result;
}

- (ProcessIdList*) defaultInstance;

- (ProcessIdList_Builder*) clear;
- (ProcessIdList_Builder*) clone;

- (ProcessIdList*) build;
- (ProcessIdList*) buildPartial;

- (ProcessIdList_Builder*) mergeFrom:(ProcessIdList*) other;
- (ProcessIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProcessIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) pidList;
- (NSString*) pidAtIndex:(int32_t) index;
- (ProcessIdList_Builder*) replacePidAtIndex:(int32_t) index with:(NSString*) value;
- (ProcessIdList_Builder*) addPid:(NSString*) value;
- (ProcessIdList_Builder*) addAllPid:(NSArray*) values;
- (ProcessIdList_Builder*) clearPidList;
@end

