// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ProcessTypeIdList;
@class ProcessTypeIdList_Builder;

@interface ProcessTypeIdListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ProcessTypeIdList : PBGeneratedMessage {
@private
  NSMutableArray* mutableProcessTypeIdList;
}
- (NSArray*) processTypeIdList;
- (NSString*) processTypeIdAtIndex:(int32_t) index;

+ (ProcessTypeIdList*) defaultInstance;
- (ProcessTypeIdList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProcessTypeIdList_Builder*) builder;
+ (ProcessTypeIdList_Builder*) builder;
+ (ProcessTypeIdList_Builder*) builderWithPrototype:(ProcessTypeIdList*) prototype;

+ (ProcessTypeIdList*) parseFromData:(NSData*) data;
+ (ProcessTypeIdList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessTypeIdList*) parseFromInputStream:(NSInputStream*) input;
+ (ProcessTypeIdList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessTypeIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProcessTypeIdList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProcessTypeIdList_Builder : PBGeneratedMessage_Builder {
@private
  ProcessTypeIdList* result;
}

- (ProcessTypeIdList*) defaultInstance;

- (ProcessTypeIdList_Builder*) clear;
- (ProcessTypeIdList_Builder*) clone;

- (ProcessTypeIdList*) build;
- (ProcessTypeIdList*) buildPartial;

- (ProcessTypeIdList_Builder*) mergeFrom:(ProcessTypeIdList*) other;
- (ProcessTypeIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProcessTypeIdList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) processTypeIdList;
- (NSString*) processTypeIdAtIndex:(int32_t) index;
- (ProcessTypeIdList_Builder*) replaceProcessTypeIdAtIndex:(int32_t) index with:(NSString*) value;
- (ProcessTypeIdList_Builder*) addProcessTypeId:(NSString*) value;
- (ProcessTypeIdList_Builder*) addAllProcessTypeId:(NSArray*) values;
- (ProcessTypeIdList_Builder*) clearProcessTypeIdList;
@end

