// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class A_Basket_ProcessId_And_Date;
@class A_Basket_ProcessId_And_Date_Builder;
@class All_Baskets_ProcessId_And_Date;
@class All_Baskets_ProcessId_And_Date_Builder;
@class Document;
@class DocumentList;
@class DocumentList_Builder;
@class Document_Builder;
@class Error;
@class Error_Builder;
@class Index;
@class IndexList;
@class IndexList_Builder;
@class Index_Builder;
@class Process;
@class ProcessList;
@class ProcessList_Builder;
@class Process_Builder;

@interface SivapbfRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Error : PBGeneratedMessage {
@private
  BOOL hasErrCode_:1;
  BOOL hasErrText_:1;
  int32_t errCode;
  NSString* errText;
}
- (BOOL) hasErrCode;
- (BOOL) hasErrText;
@property (readonly) int32_t errCode;
@property (readonly, retain) NSString* errText;

+ (Error*) defaultInstance;
- (Error*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Error_Builder*) builder;
+ (Error_Builder*) builder;
+ (Error_Builder*) builderWithPrototype:(Error*) prototype;

+ (Error*) parseFromData:(NSData*) data;
+ (Error*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Error*) parseFromInputStream:(NSInputStream*) input;
+ (Error*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Error*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Error*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Error_Builder : PBGeneratedMessage_Builder {
@private
  Error* result;
}

- (Error*) defaultInstance;

- (Error_Builder*) clear;
- (Error_Builder*) clone;

- (Error*) build;
- (Error*) buildPartial;

- (Error_Builder*) mergeFrom:(Error*) other;
- (Error_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Error_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrCode;
- (int32_t) errCode;
- (Error_Builder*) setErrCode:(int32_t) value;
- (Error_Builder*) clearErrCode;

- (BOOL) hasErrText;
- (NSString*) errText;
- (Error_Builder*) setErrText:(NSString*) value;
- (Error_Builder*) clearErrText;
@end

@interface A_Basket_ProcessId_And_Date : PBGeneratedMessage {
@private
  BOOL hasBasketId_:1;
  BOOL hasLastBuildDate_:1;
  NSString* basketId;
  NSString* lastBuildDate;
  NSMutableArray* mutablePIdList;
}
- (BOOL) hasBasketId;
- (BOOL) hasLastBuildDate;
@property (readonly, retain) NSString* basketId;
@property (readonly, retain) NSString* lastBuildDate;
- (NSArray*) pIdList;
- (NSString*) pIdAtIndex:(int32_t) index;

+ (A_Basket_ProcessId_And_Date*) defaultInstance;
- (A_Basket_ProcessId_And_Date*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (A_Basket_ProcessId_And_Date_Builder*) builder;
+ (A_Basket_ProcessId_And_Date_Builder*) builder;
+ (A_Basket_ProcessId_And_Date_Builder*) builderWithPrototype:(A_Basket_ProcessId_And_Date*) prototype;

+ (A_Basket_ProcessId_And_Date*) parseFromData:(NSData*) data;
+ (A_Basket_ProcessId_And_Date*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (A_Basket_ProcessId_And_Date*) parseFromInputStream:(NSInputStream*) input;
+ (A_Basket_ProcessId_And_Date*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (A_Basket_ProcessId_And_Date*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (A_Basket_ProcessId_And_Date*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface A_Basket_ProcessId_And_Date_Builder : PBGeneratedMessage_Builder {
@private
  A_Basket_ProcessId_And_Date* result;
}

- (A_Basket_ProcessId_And_Date*) defaultInstance;

- (A_Basket_ProcessId_And_Date_Builder*) clear;
- (A_Basket_ProcessId_And_Date_Builder*) clone;

- (A_Basket_ProcessId_And_Date*) build;
- (A_Basket_ProcessId_And_Date*) buildPartial;

- (A_Basket_ProcessId_And_Date_Builder*) mergeFrom:(A_Basket_ProcessId_And_Date*) other;
- (A_Basket_ProcessId_And_Date_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (A_Basket_ProcessId_And_Date_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBasketId;
- (NSString*) basketId;
- (A_Basket_ProcessId_And_Date_Builder*) setBasketId:(NSString*) value;
- (A_Basket_ProcessId_And_Date_Builder*) clearBasketId;

- (BOOL) hasLastBuildDate;
- (NSString*) lastBuildDate;
- (A_Basket_ProcessId_And_Date_Builder*) setLastBuildDate:(NSString*) value;
- (A_Basket_ProcessId_And_Date_Builder*) clearLastBuildDate;

- (NSArray*) pIdList;
- (NSString*) pIdAtIndex:(int32_t) index;
- (A_Basket_ProcessId_And_Date_Builder*) replacePIdAtIndex:(int32_t) index with:(NSString*) value;
- (A_Basket_ProcessId_And_Date_Builder*) addPId:(NSString*) value;
- (A_Basket_ProcessId_And_Date_Builder*) addAllPId:(NSArray*) values;
- (A_Basket_ProcessId_And_Date_Builder*) clearPIdList;
@end

@interface All_Baskets_ProcessId_And_Date : PBGeneratedMessage {
@private
  NSMutableArray* mutableABasketProcessIdAndDateList;
}
- (NSArray*) aBasketProcessIdAndDateList;
- (A_Basket_ProcessId_And_Date*) aBasketProcessIdAndDateAtIndex:(int32_t) index;

+ (All_Baskets_ProcessId_And_Date*) defaultInstance;
- (All_Baskets_ProcessId_And_Date*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (All_Baskets_ProcessId_And_Date_Builder*) builder;
+ (All_Baskets_ProcessId_And_Date_Builder*) builder;
+ (All_Baskets_ProcessId_And_Date_Builder*) builderWithPrototype:(All_Baskets_ProcessId_And_Date*) prototype;

+ (All_Baskets_ProcessId_And_Date*) parseFromData:(NSData*) data;
+ (All_Baskets_ProcessId_And_Date*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (All_Baskets_ProcessId_And_Date*) parseFromInputStream:(NSInputStream*) input;
+ (All_Baskets_ProcessId_And_Date*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (All_Baskets_ProcessId_And_Date*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (All_Baskets_ProcessId_And_Date*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface All_Baskets_ProcessId_And_Date_Builder : PBGeneratedMessage_Builder {
@private
  All_Baskets_ProcessId_And_Date* result;
}

- (All_Baskets_ProcessId_And_Date*) defaultInstance;

- (All_Baskets_ProcessId_And_Date_Builder*) clear;
- (All_Baskets_ProcessId_And_Date_Builder*) clone;

- (All_Baskets_ProcessId_And_Date*) build;
- (All_Baskets_ProcessId_And_Date*) buildPartial;

- (All_Baskets_ProcessId_And_Date_Builder*) mergeFrom:(All_Baskets_ProcessId_And_Date*) other;
- (All_Baskets_ProcessId_And_Date_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (All_Baskets_ProcessId_And_Date_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) aBasketProcessIdAndDateList;
- (A_Basket_ProcessId_And_Date*) aBasketProcessIdAndDateAtIndex:(int32_t) index;
- (All_Baskets_ProcessId_And_Date_Builder*) replaceABasketProcessIdAndDateAtIndex:(int32_t) index with:(A_Basket_ProcessId_And_Date*) value;
- (All_Baskets_ProcessId_And_Date_Builder*) addABasketProcessIdAndDate:(A_Basket_ProcessId_And_Date*) value;
- (All_Baskets_ProcessId_And_Date_Builder*) addAllABasketProcessIdAndDate:(NSArray*) values;
- (All_Baskets_ProcessId_And_Date_Builder*) clearABasketProcessIdAndDateList;
@end

@interface Index : PBGeneratedMessage {
@private
  BOOL hasIndexId_:1;
  BOOL hasIndexValue_:1;
  NSString* indexId;
  NSString* indexValue;
}
- (BOOL) hasIndexId;
- (BOOL) hasIndexValue;
@property (readonly, retain) NSString* indexId;
@property (readonly, retain) NSString* indexValue;

+ (Index*) defaultInstance;
- (Index*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Index_Builder*) builder;
+ (Index_Builder*) builder;
+ (Index_Builder*) builderWithPrototype:(Index*) prototype;

+ (Index*) parseFromData:(NSData*) data;
+ (Index*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Index*) parseFromInputStream:(NSInputStream*) input;
+ (Index*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Index*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Index*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Index_Builder : PBGeneratedMessage_Builder {
@private
  Index* result;
}

- (Index*) defaultInstance;

- (Index_Builder*) clear;
- (Index_Builder*) clone;

- (Index*) build;
- (Index*) buildPartial;

- (Index_Builder*) mergeFrom:(Index*) other;
- (Index_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Index_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIndexId;
- (NSString*) indexId;
- (Index_Builder*) setIndexId:(NSString*) value;
- (Index_Builder*) clearIndexId;

- (BOOL) hasIndexValue;
- (NSString*) indexValue;
- (Index_Builder*) setIndexValue:(NSString*) value;
- (Index_Builder*) clearIndexValue;
@end

@interface IndexList : PBGeneratedMessage {
@private
  NSMutableArray* mutableIndexList;
}
- (NSArray*) indexList;
- (Index*) indexAtIndex:(int32_t) index;

+ (IndexList*) defaultInstance;
- (IndexList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IndexList_Builder*) builder;
+ (IndexList_Builder*) builder;
+ (IndexList_Builder*) builderWithPrototype:(IndexList*) prototype;

+ (IndexList*) parseFromData:(NSData*) data;
+ (IndexList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IndexList*) parseFromInputStream:(NSInputStream*) input;
+ (IndexList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IndexList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IndexList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IndexList_Builder : PBGeneratedMessage_Builder {
@private
  IndexList* result;
}

- (IndexList*) defaultInstance;

- (IndexList_Builder*) clear;
- (IndexList_Builder*) clone;

- (IndexList*) build;
- (IndexList*) buildPartial;

- (IndexList_Builder*) mergeFrom:(IndexList*) other;
- (IndexList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IndexList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) indexList;
- (Index*) indexAtIndex:(int32_t) index;
- (IndexList_Builder*) replaceIndexAtIndex:(int32_t) index with:(Index*) value;
- (IndexList_Builder*) addIndex:(Index*) value;
- (IndexList_Builder*) addAllIndex:(NSArray*) values;
- (IndexList_Builder*) clearIndexList;
@end

@interface Document : PBGeneratedMessage {
@private
  BOOL hasPageCount_:1;
  BOOL hasDId_:1;
  BOOL hasTypeId_:1;
  BOOL hasIndexList_:1;
  int32_t pageCount;
  NSString* dId;
  NSString* typeId;
  IndexList* indexList;
}
- (BOOL) hasDId;
- (BOOL) hasTypeId;
- (BOOL) hasPageCount;
- (BOOL) hasIndexList;
@property (readonly, retain) NSString* dId;
@property (readonly, retain) NSString* typeId;
@property (readonly) int32_t pageCount;
@property (readonly, retain) IndexList* indexList;

+ (Document*) defaultInstance;
- (Document*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Document_Builder*) builder;
+ (Document_Builder*) builder;
+ (Document_Builder*) builderWithPrototype:(Document*) prototype;

+ (Document*) parseFromData:(NSData*) data;
+ (Document*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Document*) parseFromInputStream:(NSInputStream*) input;
+ (Document*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Document*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Document*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Document_Builder : PBGeneratedMessage_Builder {
@private
  Document* result;
}

- (Document*) defaultInstance;

- (Document_Builder*) clear;
- (Document_Builder*) clone;

- (Document*) build;
- (Document*) buildPartial;

- (Document_Builder*) mergeFrom:(Document*) other;
- (Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Document_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDId;
- (NSString*) dId;
- (Document_Builder*) setDId:(NSString*) value;
- (Document_Builder*) clearDId;

- (BOOL) hasTypeId;
- (NSString*) typeId;
- (Document_Builder*) setTypeId:(NSString*) value;
- (Document_Builder*) clearTypeId;

- (BOOL) hasPageCount;
- (int32_t) pageCount;
- (Document_Builder*) setPageCount:(int32_t) value;
- (Document_Builder*) clearPageCount;

- (BOOL) hasIndexList;
- (IndexList*) indexList;
- (Document_Builder*) setIndexList:(IndexList*) value;
- (Document_Builder*) setIndexListBuilder:(IndexList_Builder*) builderForValue;
- (Document_Builder*) mergeIndexList:(IndexList*) value;
- (Document_Builder*) clearIndexList;
@end

@interface DocumentList : PBGeneratedMessage {
@private
  NSMutableArray* mutableDocumentList;
}
- (NSArray*) documentList;
- (Document*) documentAtIndex:(int32_t) index;

+ (DocumentList*) defaultInstance;
- (DocumentList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DocumentList_Builder*) builder;
+ (DocumentList_Builder*) builder;
+ (DocumentList_Builder*) builderWithPrototype:(DocumentList*) prototype;

+ (DocumentList*) parseFromData:(NSData*) data;
+ (DocumentList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DocumentList*) parseFromInputStream:(NSInputStream*) input;
+ (DocumentList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DocumentList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DocumentList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DocumentList_Builder : PBGeneratedMessage_Builder {
@private
  DocumentList* result;
}

- (DocumentList*) defaultInstance;

- (DocumentList_Builder*) clear;
- (DocumentList_Builder*) clone;

- (DocumentList*) build;
- (DocumentList*) buildPartial;

- (DocumentList_Builder*) mergeFrom:(DocumentList*) other;
- (DocumentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DocumentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) documentList;
- (Document*) documentAtIndex:(int32_t) index;
- (DocumentList_Builder*) replaceDocumentAtIndex:(int32_t) index with:(Document*) value;
- (DocumentList_Builder*) addDocument:(Document*) value;
- (DocumentList_Builder*) addAllDocument:(NSArray*) values;
- (DocumentList_Builder*) clearDocumentList;
@end

@interface Process : PBGeneratedMessage {
@private
  BOOL hasPId_:1;
  BOOL hasOrderId_:1;
  BOOL hasTypeId_:1;
  BOOL hasEntryDate_:1;
  BOOL hasResubmitDate_:1;
  BOOL hasIndexList_:1;
  BOOL hasDocumentList_:1;
  NSString* pId;
  NSString* orderId;
  NSString* typeId;
  NSString* entryDate;
  NSString* resubmitDate;
  IndexList* indexList;
  DocumentList* documentList;
}
- (BOOL) hasPId;
- (BOOL) hasOrderId;
- (BOOL) hasTypeId;
- (BOOL) hasEntryDate;
- (BOOL) hasResubmitDate;
- (BOOL) hasIndexList;
- (BOOL) hasDocumentList;
@property (readonly, retain) NSString* pId;
@property (readonly, retain) NSString* orderId;
@property (readonly, retain) NSString* typeId;
@property (readonly, retain) NSString* entryDate;
@property (readonly, retain) NSString* resubmitDate;
@property (readonly, retain) IndexList* indexList;
@property (readonly, retain) DocumentList* documentList;

+ (Process*) defaultInstance;
- (Process*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Process_Builder*) builder;
+ (Process_Builder*) builder;
+ (Process_Builder*) builderWithPrototype:(Process*) prototype;

+ (Process*) parseFromData:(NSData*) data;
+ (Process*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Process*) parseFromInputStream:(NSInputStream*) input;
+ (Process*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Process*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Process*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Process_Builder : PBGeneratedMessage_Builder {
@private
  Process* result;
}

- (Process*) defaultInstance;

- (Process_Builder*) clear;
- (Process_Builder*) clone;

- (Process*) build;
- (Process*) buildPartial;

- (Process_Builder*) mergeFrom:(Process*) other;
- (Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Process_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPId;
- (NSString*) pId;
- (Process_Builder*) setPId:(NSString*) value;
- (Process_Builder*) clearPId;

- (BOOL) hasOrderId;
- (NSString*) orderId;
- (Process_Builder*) setOrderId:(NSString*) value;
- (Process_Builder*) clearOrderId;

- (BOOL) hasTypeId;
- (NSString*) typeId;
- (Process_Builder*) setTypeId:(NSString*) value;
- (Process_Builder*) clearTypeId;

- (BOOL) hasEntryDate;
- (NSString*) entryDate;
- (Process_Builder*) setEntryDate:(NSString*) value;
- (Process_Builder*) clearEntryDate;

- (BOOL) hasResubmitDate;
- (NSString*) resubmitDate;
- (Process_Builder*) setResubmitDate:(NSString*) value;
- (Process_Builder*) clearResubmitDate;

- (BOOL) hasIndexList;
- (IndexList*) indexList;
- (Process_Builder*) setIndexList:(IndexList*) value;
- (Process_Builder*) setIndexListBuilder:(IndexList_Builder*) builderForValue;
- (Process_Builder*) mergeIndexList:(IndexList*) value;
- (Process_Builder*) clearIndexList;

- (BOOL) hasDocumentList;
- (DocumentList*) documentList;
- (Process_Builder*) setDocumentList:(DocumentList*) value;
- (Process_Builder*) setDocumentListBuilder:(DocumentList_Builder*) builderForValue;
- (Process_Builder*) mergeDocumentList:(DocumentList*) value;
- (Process_Builder*) clearDocumentList;
@end

@interface ProcessList : PBGeneratedMessage {
@private
  NSMutableArray* mutableProcessList;
}
- (NSArray*) processList;
- (Process*) processAtIndex:(int32_t) index;

+ (ProcessList*) defaultInstance;
- (ProcessList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProcessList_Builder*) builder;
+ (ProcessList_Builder*) builder;
+ (ProcessList_Builder*) builderWithPrototype:(ProcessList*) prototype;

+ (ProcessList*) parseFromData:(NSData*) data;
+ (ProcessList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessList*) parseFromInputStream:(NSInputStream*) input;
+ (ProcessList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProcessList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProcessList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProcessList_Builder : PBGeneratedMessage_Builder {
@private
  ProcessList* result;
}

- (ProcessList*) defaultInstance;

- (ProcessList_Builder*) clear;
- (ProcessList_Builder*) clone;

- (ProcessList*) build;
- (ProcessList*) buildPartial;

- (ProcessList_Builder*) mergeFrom:(ProcessList*) other;
- (ProcessList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProcessList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) processList;
- (Process*) processAtIndex:(int32_t) index;
- (ProcessList_Builder*) replaceProcessAtIndex:(int32_t) index with:(Process*) value;
- (ProcessList_Builder*) addProcess:(Process*) value;
- (ProcessList_Builder*) addAllProcess:(NSArray*) values;
- (ProcessList_Builder*) clearProcessList;
@end

