// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Wb;
@class WbList;
@class WbList_Builder;
@class Wb_Builder;

@interface WbListRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Wb : PBGeneratedMessage {
@private
  BOOL hasInGroupId_:1;
  BOOL hasUnread_:1;
  BOOL hasTotal_:1;
  BOOL hasId_:1;
  BOOL hasType_:1;
  BOOL hasName_:1;
  BOOL hasLastBuildDate_:1;
  BOOL hasInMandantId_:1;
  int32_t inGroupId;
  int32_t unread;
  int32_t total;
  NSString* id;
  NSString* type;
  NSString* name;
  NSString* lastBuildDate;
  NSString* inMandantId;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasName;
- (BOOL) hasLastBuildDate;
- (BOOL) hasInMandantId;
- (BOOL) hasInGroupId;
- (BOOL) hasUnread;
- (BOOL) hasTotal;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* type;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* lastBuildDate;
@property (readonly, retain) NSString* inMandantId;
@property (readonly) int32_t inGroupId;
@property (readonly) int32_t unread;
@property (readonly) int32_t total;

+ (Wb*) defaultInstance;
- (Wb*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Wb_Builder*) builder;
+ (Wb_Builder*) builder;
+ (Wb_Builder*) builderWithPrototype:(Wb*) prototype;

+ (Wb*) parseFromData:(NSData*) data;
+ (Wb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Wb*) parseFromInputStream:(NSInputStream*) input;
+ (Wb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Wb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Wb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Wb_Builder : PBGeneratedMessage_Builder {
@private
  Wb* result;
}

- (Wb*) defaultInstance;

- (Wb_Builder*) clear;
- (Wb_Builder*) clone;

- (Wb*) build;
- (Wb*) buildPartial;

- (Wb_Builder*) mergeFrom:(Wb*) other;
- (Wb_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Wb_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (Wb_Builder*) setId:(NSString*) value;
- (Wb_Builder*) clearId;

- (BOOL) hasType;
- (NSString*) type;
- (Wb_Builder*) setType:(NSString*) value;
- (Wb_Builder*) clearType;

- (BOOL) hasName;
- (NSString*) name;
- (Wb_Builder*) setName:(NSString*) value;
- (Wb_Builder*) clearName;

- (BOOL) hasLastBuildDate;
- (NSString*) lastBuildDate;
- (Wb_Builder*) setLastBuildDate:(NSString*) value;
- (Wb_Builder*) clearLastBuildDate;

- (BOOL) hasInMandantId;
- (NSString*) inMandantId;
- (Wb_Builder*) setInMandantId:(NSString*) value;
- (Wb_Builder*) clearInMandantId;

- (BOOL) hasInGroupId;
- (int32_t) inGroupId;
- (Wb_Builder*) setInGroupId:(int32_t) value;
- (Wb_Builder*) clearInGroupId;

- (BOOL) hasUnread;
- (int32_t) unread;
- (Wb_Builder*) setUnread:(int32_t) value;
- (Wb_Builder*) clearUnread;

- (BOOL) hasTotal;
- (int32_t) total;
- (Wb_Builder*) setTotal:(int32_t) value;
- (Wb_Builder*) clearTotal;
@end

@interface WbList : PBGeneratedMessage {
@private
  NSMutableArray* mutableWbList;
}
- (NSArray*) wbList;
- (Wb*) wbAtIndex:(int32_t) index;

+ (WbList*) defaultInstance;
- (WbList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WbList_Builder*) builder;
+ (WbList_Builder*) builder;
+ (WbList_Builder*) builderWithPrototype:(WbList*) prototype;

+ (WbList*) parseFromData:(NSData*) data;
+ (WbList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WbList*) parseFromInputStream:(NSInputStream*) input;
+ (WbList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WbList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WbList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WbList_Builder : PBGeneratedMessage_Builder {
@private
  WbList* result;
}

- (WbList*) defaultInstance;

- (WbList_Builder*) clear;
- (WbList_Builder*) clone;

- (WbList*) build;
- (WbList*) buildPartial;

- (WbList_Builder*) mergeFrom:(WbList*) other;
- (WbList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WbList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) wbList;
- (Wb*) wbAtIndex:(int32_t) index;
- (WbList_Builder*) replaceWbAtIndex:(int32_t) index with:(Wb*) value;
- (WbList_Builder*) addWb:(Wb*) value;
- (WbList_Builder*) addAllWb:(NSArray*) values;
- (WbList_Builder*) clearWbList;
@end

