// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "WbList.pb.h"

@implementation WbListRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [WbListRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Wb ()
@property (retain) NSString* id;
@property (retain) NSString* type;
@property (retain) NSString* name;
@property (retain) NSString* lastBuildDate;
@property (retain) NSString* inMandantId;
@property int32_t inGroupId;
@property int32_t unread;
@property int32_t total;
@end

@implementation Wb

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value {
  hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value {
  hasType_ = !!value;
}
@synthesize type;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasLastBuildDate {
  return !!hasLastBuildDate_;
}
- (void) setHasLastBuildDate:(BOOL) value {
  hasLastBuildDate_ = !!value;
}
@synthesize lastBuildDate;
- (BOOL) hasInMandantId {
  return !!hasInMandantId_;
}
- (void) setHasInMandantId:(BOOL) value {
  hasInMandantId_ = !!value;
}
@synthesize inMandantId;
- (BOOL) hasInGroupId {
  return !!hasInGroupId_;
}
- (void) setHasInGroupId:(BOOL) value {
  hasInGroupId_ = !!value;
}
@synthesize inGroupId;
- (BOOL) hasUnread {
  return !!hasUnread_;
}
- (void) setHasUnread:(BOOL) value {
  hasUnread_ = !!value;
}
@synthesize unread;
- (BOOL) hasTotal {
  return !!hasTotal_;
}
- (void) setHasTotal:(BOOL) value {
  hasTotal_ = !!value;
}
@synthesize total;
- (void) dealloc {
  self.id = nil;
  self.type = nil;
  self.name = nil;
  self.lastBuildDate = nil;
  self.inMandantId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.type = @"";
    self.name = @"";
    self.lastBuildDate = @"";
    self.inMandantId = @"";
    self.inGroupId = 0;
    self.unread = 0;
    self.total = 0;  
  }
  return self;
}

// INIT SERVER WB
- (id) initWithId:(NSString*)idPar inMandantId:(NSString*)inMandantIdPar type:(NSString*)typePar {
	if ((self = [super init])) {
		self.id = idPar;
		self.name=idPar; //temporarily
		self.type = typePar;			
		self.inMandantId = inMandantIdPar;
		self.inGroupId = 0;
		self.unread = 0;
		self.total = 0;
	}
	return self;
}

// INIT DB WB
-(id)initWithId:(NSString*)idPar inMandantId:(NSString*)inMandantIdPar name:(NSString*)namePar inGroupId:(int)inGroupIdPar{
	self=[super init];
	if (self) {				
		self.id = idPar;
		self.type = @"";
		self.name = namePar;
		self.lastBuildDate = @"";
		self.inMandantId = inMandantIdPar;
		self.inGroupId = inGroupIdPar;
		self.unread = 0;
		self.total = 0;
	}
	return self;
}


static Wb* defaultWbInstance = nil;
+ (void) initialize {
  if (self == [Wb class]) {
    defaultWbInstance = [[Wb alloc] init];
  }
}
+ (Wb*) defaultInstance {
  return defaultWbInstance;
}
- (Wb*) defaultInstance {
  return defaultWbInstance;
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasType) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasType) {
    [output writeString:2 value:self.type];
  }
  if (self.hasName) {
    [output writeString:3 value:self.name];
  }
  if (self.hasLastBuildDate) {
    [output writeString:4 value:self.lastBuildDate];
  }
  if (self.hasInMandantId) {
    [output writeString:5 value:self.inMandantId];
  }
  if (self.hasInGroupId) {
    [output writeInt32:6 value:self.inGroupId];
  }
  if (self.hasUnread) {
    [output writeInt32:7 value:self.unread];
  }
  if (self.hasTotal) {
    [output writeInt32:8 value:self.total];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasType) {
    size += computeStringSize(2, self.type);
  }
  if (self.hasName) {
    size += computeStringSize(3, self.name);
  }
  if (self.hasLastBuildDate) {
    size += computeStringSize(4, self.lastBuildDate);
  }
  if (self.hasInMandantId) {
    size += computeStringSize(5, self.inMandantId);
  }
  if (self.hasInGroupId) {
    size += computeInt32Size(6, self.inGroupId);
  }
  if (self.hasUnread) {
    size += computeInt32Size(7, self.unread);
  }
  if (self.hasTotal) {
    size += computeInt32Size(8, self.total);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Wb*) parseFromData:(NSData*) data {
  return (Wb*)[[[Wb builder] mergeFromData:data] build];
}
+ (Wb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Wb*)[[[Wb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Wb*) parseFromInputStream:(NSInputStream*) input {
  return (Wb*)[[[Wb builder] mergeFromInputStream:input] build];
}
+ (Wb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Wb*)[[[Wb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Wb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Wb*)[[[Wb builder] mergeFromCodedInputStream:input] build];
}
+ (Wb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Wb*)[[[Wb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Wb_Builder*) builder {
  return [[[Wb_Builder alloc] init] autorelease];
}
+ (Wb_Builder*) builderWithPrototype:(Wb*) prototype {
  return [[Wb builder] mergeFrom:prototype];
}
- (Wb_Builder*) builder {
  return [Wb builder];
}
@end

@interface Wb_Builder()
@property (retain) Wb* result;
@end

@implementation Wb_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Wb alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Wb_Builder*) clear {
  self.result = [[[Wb alloc] init] autorelease];
  return self;
}
- (Wb_Builder*) clone {
  return [Wb builderWithPrototype:result];
}
- (Wb*) defaultInstance {
  return [Wb defaultInstance];
}
- (Wb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Wb*) buildPartial {
  Wb* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Wb_Builder*) mergeFrom:(Wb*) other {
  if (other == [Wb defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasLastBuildDate) {
    [self setLastBuildDate:other.lastBuildDate];
  }
  if (other.hasInMandantId) {
    [self setInMandantId:other.inMandantId];
  }
  if (other.hasInGroupId) {
    [self setInGroupId:other.inGroupId];
  }
  if (other.hasUnread) {
    [self setUnread:other.unread];
  }
  if (other.hasTotal) {
    [self setTotal:other.total];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Wb_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Wb_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setType:[input readString]];
        break;
      }
      case 26: {
        [self setName:[input readString]];
        break;
      }
      case 34: {
        [self setLastBuildDate:[input readString]];
        break;
      }
      case 42: {
        [self setInMandantId:[input readString]];
        break;
      }
      case 48: {
        [self setInGroupId:[input readInt32]];
        break;
      }
      case 56: {
        [self setUnread:[input readInt32]];
        break;
      }
      case 64: {
        [self setTotal:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (NSString*) id {
  return result.id;
}
- (Wb_Builder*) setId:(NSString*) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (Wb_Builder*) clearId {
  result.hasId = NO;
  result.id = @"";
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (NSString*) type {
  return result.type;
}
- (Wb_Builder*) setType:(NSString*) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (Wb_Builder*) clearType {
  result.hasType = NO;
  result.type = @"";
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (Wb_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (Wb_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasLastBuildDate {
  return result.hasLastBuildDate;
}
- (NSString*) lastBuildDate {
  return result.lastBuildDate;
}
- (Wb_Builder*) setLastBuildDate:(NSString*) value {
  result.hasLastBuildDate = YES;
  result.lastBuildDate = value;
  return self;
}
- (Wb_Builder*) clearLastBuildDate {
  result.hasLastBuildDate = NO;
  result.lastBuildDate = @"";
  return self;
}
- (BOOL) hasInMandantId {
  return result.hasInMandantId;
}
- (NSString*) inMandantId {
  return result.inMandantId;
}
- (Wb_Builder*) setInMandantId:(NSString*) value {
  result.hasInMandantId = YES;
  result.inMandantId = value;
  return self;
}
- (Wb_Builder*) clearInMandantId {
  result.hasInMandantId = NO;
  result.inMandantId = @"";
  return self;
}
- (BOOL) hasInGroupId {
  return result.hasInGroupId;
}
- (int32_t) inGroupId {
  return result.inGroupId;
}
- (Wb_Builder*) setInGroupId:(int32_t) value {
  result.hasInGroupId = YES;
  result.inGroupId = value;
  return self;
}
- (Wb_Builder*) clearInGroupId {
  result.hasInGroupId = NO;
  result.inGroupId = 0;
  return self;
}
- (BOOL) hasUnread {
  return result.hasUnread;
}
- (int32_t) unread {
  return result.unread;
}
- (Wb_Builder*) setUnread:(int32_t) value {
  result.hasUnread = YES;
  result.unread = value;
  return self;
}
- (Wb_Builder*) clearUnread {
  result.hasUnread = NO;
  result.unread = 0;
  return self;
}
- (BOOL) hasTotal {
  return result.hasTotal;
}
- (int32_t) total {
  return result.total;
}
- (Wb_Builder*) setTotal:(int32_t) value {
  result.hasTotal = YES;
  result.total = value;
  return self;
}
- (Wb_Builder*) clearTotal {
  result.hasTotal = NO;
  result.total = 0;
  return self;
}
@end

@interface WbList ()
@property (retain) NSMutableArray* mutableWbList;
@end

@implementation WbList

@synthesize mutableWbList;
- (void) dealloc {
  self.mutableWbList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static WbList* defaultWbListInstance = nil;
+ (void) initialize {
  if (self == [WbList class]) {
    defaultWbListInstance = [[WbList alloc] init];
  }
}
+ (WbList*) defaultInstance {
  return defaultWbListInstance;
}
- (WbList*) defaultInstance {
  return defaultWbListInstance;
}
- (NSArray*) wbList {
  return mutableWbList;
}
- (Wb*) wbAtIndex:(int32_t) index {
  id value = [mutableWbList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  for (Wb* element in self.wbList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (Wb* element in self.wbList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (Wb* element in self.wbList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (WbList*) parseFromData:(NSData*) data {
  return (WbList*)[[[WbList builder] mergeFromData:data] build];
}
+ (WbList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (WbList*)[[[WbList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (WbList*) parseFromInputStream:(NSInputStream*) input {
  return (WbList*)[[[WbList builder] mergeFromInputStream:input] build];
}
+ (WbList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (WbList*)[[[WbList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (WbList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (WbList*)[[[WbList builder] mergeFromCodedInputStream:input] build];
}
+ (WbList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (WbList*)[[[WbList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (WbList_Builder*) builder {
  return [[[WbList_Builder alloc] init] autorelease];
}
+ (WbList_Builder*) builderWithPrototype:(WbList*) prototype {
  return [[WbList builder] mergeFrom:prototype];
}
- (WbList_Builder*) builder {
  return [WbList builder];
}
@end

@interface WbList_Builder()
@property (retain) WbList* result;
@end

@implementation WbList_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[WbList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (WbList_Builder*) clear {
  self.result = [[[WbList alloc] init] autorelease];
  return self;
}
- (WbList_Builder*) clone {
  return [WbList builderWithPrototype:result];
}
- (WbList*) defaultInstance {
  return [WbList defaultInstance];
}
- (WbList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (WbList*) buildPartial {
  WbList* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (WbList_Builder*) mergeFrom:(WbList*) other {
  if (other == [WbList defaultInstance]) {
    return self;
  }
  if (other.mutableWbList.count > 0) {
    if (result.mutableWbList == nil) {
      result.mutableWbList = [NSMutableArray array];
    }
    [result.mutableWbList addObjectsFromArray:other.mutableWbList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (WbList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (WbList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Wb_Builder* subBuilder = [Wb builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addWb:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) wbList {
  if (result.mutableWbList == nil) { return [NSArray array]; }
  return result.mutableWbList;
}
- (Wb*) wbAtIndex:(int32_t) index {
  return [result wbAtIndex:index];
}
- (WbList_Builder*) replaceWbAtIndex:(int32_t) index with:(Wb*) value {
  [result.mutableWbList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (WbList_Builder*) addAllWb:(NSArray*) values {
  if (result.mutableWbList == nil) {
    result.mutableWbList = [NSMutableArray array];
  }
  [result.mutableWbList addObjectsFromArray:values];
  return self;
}
- (WbList_Builder*) clearWbList {
  result.mutableWbList = nil;
  return self;
}
- (WbList_Builder*) addWb:(Wb*) value {
  if (result.mutableWbList == nil) {
    result.mutableWbList = [NSMutableArray array];
  }
  [result.mutableWbList addObject:value];
  return self;
}
@end

